import { createHmac } from "node:crypto";

import { expect, test } from "@playwright/test";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";

const url=process.env.SUPABASE_TEST_URL??"";const key=process.env.SUPABASE_TEST_SECRET_KEY??"";const run=`phase8d-${Date.now()}-${Math.random().toString(16).slice(2,10)}`;const email=`${run}-owner@example.test`;const password="SyntheticAdmin42!";let admin:SupabaseClient;let owner:User;let adminId="";
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const character of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(character).toString(2).padStart(5,"0");const bytes=[];for(let offset=0;offset+8<=bits.length;offset+=8)bytes.push(Number.parseInt(bits.slice(offset,offset+8),2));return Buffer.from(bytes)}
function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest();const offset=digest[digest.length-1]&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,"0")}
const safePdf=(title:string)=>Buffer.from(`%PDF-1.7\n1 0 obj << /Type /Catalog /AcroForm 2 0 R >> endobj\n2 0 obj << /Fields [] /Title (${title}) >> endobj\n%%EOF`);
async function publishTaxonomyNode(rpcName:string,idKey:string,id:string,title:string,slug:string,sortOrder:number){let lockVersion=1;for(const publicationState of ["validating","ready_for_review","published"]){const result=await admin.rpc(rpcName,{p_actor_admin_id:adminId,[idKey]:id,p_expected_lock_version:lockVersion,p_title:title,p_slug:slug,p_sort_order:sortOrder,p_publication_state:publicationState});if(result.error)throw result.error;lockVersion=Number(result.data)}}

test.beforeAll(async()=>{expect(url).toMatch(/^http:\/\/127\.0\.0\.1:/);admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const created=await admin.auth.admin.createUser({email,password,email_confirm:true});if(created.error||!created.data.user)throw created.error??new Error("Owner fixture unavailable");owner=created.data.user;const row=await admin.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false}).select("id").single();if(row.error)throw row.error;adminId=row.data.id});
test.afterAll(async()=>{if(owner)await admin.auth.admin.deleteUser(owner.id)});

test("owner reopens a stable Homework draft and publishes a Topic-level Quiz",async({page})=>{
  await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);

  const gradeSlug=`grade-6-${run.slice(-6)}`;const topicSlug=`ratios-${run.slice(-6)}`;const lessonSlug=`equivalent-ratios-${run.slice(-6)}`;
  const grade=await admin.rpc("create_content_grade",{p_actor_admin_id:adminId,p_grade_number:6,p_title:"Grade 6",p_slug:gradeSlug,p_sort_order:6});if(grade.error)throw grade.error;
  const topic=await admin.rpc("create_content_topic",{p_actor_admin_id:adminId,p_grade_id:grade.data,p_title:"Ratios",p_slug:topicSlug,p_sort_order:1});if(topic.error)throw topic.error;
  const lesson=await admin.rpc("create_content_lesson",{p_actor_admin_id:adminId,p_topic_id:topic.data,p_title:"Equivalent ratios",p_slug:lessonSlug,p_sort_order:1});if(lesson.error)throw lesson.error;
  await publishTaxonomyNode("update_content_grade","p_grade_id",grade.data,"Grade 6",gradeSlug,6);await publishTaxonomyNode("update_content_topic","p_topic_id",topic.data,"Ratios",topicSlug,1);await publishTaxonomyNode("update_content_lesson","p_lesson_id",lesson.data,"Equivalent ratios",lessonSlug,1);

  await page.goto("/admin?section=homework");const form=page.locator("#add-homework");await form.getByLabel("Grade for Homework").selectOption(grade.data);await form.getByLabel("Topic for Homework").selectOption(topic.data);await form.locator("select[name=lessonId]").selectOption(lesson.data);await form.getByLabel("Title",{exact:true}).fill("Equivalent ratio practice");await form.getByLabel("Slug",{exact:true}).fill("equivalent-ratio-practice");await form.getByLabel("Description").fill("Interactive owner-reviewed ratio practice.");await form.getByLabel("Tags").fill("ratios, grade-6");await form.getByLabel("Homework PDF").setInputFiles({name:"Equivalent Ratio Practice.pdf",mimeType:"application/pdf",buffer:safePdf("Homework")});await form.getByLabel("Homework Answer Key PDF").setInputFiles({name:"Equivalent Ratio Answer Key.pdf",mimeType:"application/pdf",buffer:safePdf("Answer Key")});await form.getByRole("button",{name:"Save draft"}).click();
  await expect(page).toHaveURL(/\/admin\/resources\/[0-9a-f-]+\?kind=homework&result=saved$/);const resourceId=/resources\/([0-9a-f-]+)/.exec(page.url())?.[1]??"";expect(resourceId).toMatch(/^[0-9a-f-]{36}$/);await expect(page.getByText("Draft saved.")).toBeVisible();await page.reload();await expect(page.getByRole("heading",{name:"Equivalent ratio practice"})).toBeVisible();await page.getByLabel("Description").fill("Revised owner-reviewed ratio practice.");await page.getByRole("button",{name:"Save new draft version"}).click();await expect(page).toHaveURL(new RegExp(`/admin/resources/${resourceId}\\?kind=homework&result=revised$`));await expect(page.getByText("Draft revision saved.")).toBeVisible();expect((await admin.from("content_resources").select("id",{count:"exact",head:true}).eq("id",resourceId)).count).toBe(1);
  await page.getByRole("link",{name:"Back to Homework"}).click();await expect(page).toHaveURL(/section=homework/);let row=page.locator(".admin-resource-table tbody tr").filter({has:page.getByText("Equivalent ratio practice",{exact:true})});for(const label of ["Validate","Mark ready for review","Publish"]){await row.getByRole("button",{name:label,exact:true}).click();await expect(page).toHaveURL(/publish=/);row=page.locator(".admin-resource-table tbody tr").filter({has:page.getByText("Equivalent ratio practice",{exact:true})})}expect((await admin.from("content_resources").select("publication_state").eq("id",resourceId).single()).data?.publication_state).toBe("published");
  await page.goto(`/admin/resources/${resourceId}?kind=homework`);await page.getByLabel("Title").fill("Equivalent ratio practice revised");await page.getByRole("button",{name:"Save new draft version"}).click();await page.getByRole("link",{name:"Back to Homework"}).click();row=page.locator(".admin-resource-table tbody tr").filter({has:page.getByText("Equivalent ratio practice revised",{exact:true})});await row.getByText("Version history",{exact:true}).click();await row.getByRole("button",{name:"Restore this version"}).click();await expect(page).toHaveURL(/publish=rolled-back/);expect((await admin.from("content_resource_versions").select("id",{count:"exact",head:true}).eq("resource_id",resourceId)).count).toBeGreaterThan(2);

  await page.goto("/admin?section=quizzes");const quiz=page.locator("#add-quizzes");await quiz.getByLabel("Grade for Quiz").selectOption(grade.data);await quiz.getByLabel("Topic for Quiz").selectOption(topic.data);await expect(quiz.getByLabel("Lesson")).toHaveCount(0);await expect(quiz.getByLabel("Title",{exact:true})).toHaveValue("Topic 1 Quiz: Ratios");await quiz.getByLabel("Slug",{exact:true}).fill("ratios-topic-quiz");await quiz.getByLabel("Description").fill("Reviewed topic-level ratio Quiz.");await quiz.getByLabel("Quiz PDF").setInputFiles({name:"Ratio Topic Quiz.pdf",mimeType:"application/pdf",buffer:safePdf("Ratio Quiz")});await quiz.getByRole("button",{name:"Save draft"}).click();await expect(page).toHaveURL(/kind=quizzes&result=saved/);const quizId=/resources\/([0-9a-f-]+)/.exec(page.url())?.[1]??"";const quizRow=await admin.from("content_resources").select("resource_scope,scope_status").eq("id",quizId).single();expect(quizRow.data).toMatchObject({resource_scope:"topic",scope_status:"current"});expect((await admin.from("lesson_resource_assignments").select("id",{count:"exact",head:true}).eq("resource_id",quizId)).count).toBe(0);

  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.emulateMedia({reducedMotion:"reduce",forcedColors:"active"});await expect(page.getByRole("button",{name:"Save new draft version"})).toBeVisible();
});
