import { createHmac } from "node:crypto";
import { expect,test } from "@playwright/test";
import { createClient,type SupabaseClient,type User } from "@supabase/supabase-js";
const url=process.env.SUPABASE_TEST_URL??"";const key=process.env.SUPABASE_TEST_SECRET_KEY??"";const run=`phase8d-${Date.now()}-${Math.random().toString(16).slice(2,10)}`;const email=`${run}-owner@example.test`;const password="SyntheticAdmin42!";let admin:SupabaseClient;let owner:User;let adminId="";
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const character of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(character).toString(2).padStart(5,"0");const bytes=[];for(let offset=0;offset+8<=bits.length;offset+=8)bytes.push(Number.parseInt(bits.slice(offset,offset+8),2));return Buffer.from(bytes);}
function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest();const offset=digest[digest.length-1]&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,"0");}
test.beforeAll(async()=>{expect(url).toMatch(/^http:\/\/127\.0\.0\.1:/);admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const created=await admin.auth.admin.createUser({email,password,email_confirm:true});if(created.error||!created.data.user)throw created.error;owner=created.data.user;const row=await admin.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false}).select("id").single();if(row.error)throw row.error;adminId=row.data.id;});
test.afterAll(async()=>{if(owner)await admin.auth.admin.deleteUser(owner.id);});
test("owner uploads, validates, publishes, previews, and quarantines PDFs",async({page,request})=>{
  await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);
  const grade=await admin.rpc("create_content_grade",{p_actor_admin_id:adminId,p_grade_number:6,p_title:"Grade 6",p_slug:"grade-6",p_sort_order:6});if(grade.error)throw grade.error;
  const topic=await admin.rpc("create_content_topic",{p_actor_admin_id:adminId,p_grade_id:grade.data,p_title:"Ratios",p_slug:"ratios",p_sort_order:1});if(topic.error)throw topic.error;
  const lesson=await admin.rpc("create_content_lesson",{p_actor_admin_id:adminId,p_topic_id:topic.data,p_title:"Equivalent ratios",p_slug:"equivalent-ratios",p_sort_order:1});if(lesson.error)throw lesson.error;
  await page.goto("/admin?section=homework");await page.getByLabel("Title").fill("Equivalent ratio practice");await page.getByLabel("Slug").fill("equivalent-ratio-practice");await page.getByLabel("Description").fill("Interactive owner-reviewed ratio practice.");await page.getByLabel("Tags").fill("ratios, grade-6");
  const safePdf=Buffer.from("%PDF-1.7\n1 0 obj << /Type /Catalog /AcroForm 2 0 R >> endobj\n2 0 obj << /Fields [] >> endobj\n%%EOF");
  const safeAnswerPdf=Buffer.from("%PDF-1.7\n1 0 obj << /Type /Catalog /AcroForm 2 0 R >> endobj\n2 0 obj << /Fields [] /Title (Answer Key) >> endobj\n%%EOF");
  await page.getByLabel("Interactive Homework PDF").setInputFiles({name:"Equivalent Ratio Practice.pdf",mimeType:"application/pdf",buffer:safePdf});
  await page.getByLabel("Answer Key PDF").setInputFiles({name:"Equivalent Ratio Practice Answer Key.pdf",mimeType:"application/pdf",buffer:safeAnswerPdf});
  await page.getByRole("button",{name:"Validate and save draft"}).click();await expect(page).toHaveURL(/upload=saved/);await expect(page.getByText("Draft saved.")).toBeVisible();await expect(page.getByText("equivalent-ratio-practice.pdf")).toBeVisible();
  const publishButtons=page.getByRole("button",{name:"Review and publish"});await expect(publishButtons).toHaveCount(2);await publishButtons.first().click();await expect(page).toHaveURL(/publish=published/);await page.getByRole("button",{name:"Review and publish"}).click();await expect(page).toHaveURL(/publish=published/);
  await page.goto("/homework");await expect(page.getByRole("heading",{name:"Equivalent ratio practice",exact:true})).toBeVisible();await expect(page.getByText("Answer key",{exact:true})).toBeVisible();expect(await page.locator("body").textContent()).not.toContain("resource-files");
  const primary=(await admin.from("content_resources").select("id").eq("resource_type","homework_pdf").single()).data!;const denied=await request.get(`/resources/${primary.id}/download`);expect(denied.status()).toBe(401);
  await page.goto("/admin?section=homework");await page.getByLabel("Title").fill("Unsafe ratio practice");await page.getByLabel("Slug").fill("unsafe-ratio-practice");await page.getByLabel("Description").fill("Rejected fixture.");await page.getByLabel("Order in lesson").fill("4");const unsafePdf=Buffer.from("%PDF-1.7\n1 0 obj << /Type /Catalog /OpenAction << /S /JavaScript /JS (alert) >> >> endobj\n%%EOF");await page.getByLabel("Interactive Homework PDF").setInputFiles({name:"unsafe.pdf",mimeType:"application/pdf",buffer:unsafePdf});await page.getByRole("button",{name:"Validate and save draft"}).click();await expect(page).toHaveURL(/upload=quarantined/);await expect(page.getByText("Unsafe file quarantined.")).toBeVisible();expect((await admin.from("resource_files").select("id",{count:"exact",head:true}).eq("validation_state","quarantined")).count).toBe(1);
});
