import { describe,expect,it } from "vitest";
import { compareGamePackageVersions,inspectGamePackage,normalizeGameAssetPath,parseGamePackageManifest } from "./model.js";
const bytes=(value:string)=>new TextEncoder().encode(value);async function hash(value:Uint8Array){const copy=new ArrayBuffer(value.byteLength);new Uint8Array(copy).set(value);return [...new Uint8Array(await crypto.subtle.digest("SHA-256",copy))].map(item=>item.toString(16).padStart(2,"0")).join("");}
const assets=[{path:"game/index.html",bytes:bytes('<script src="main.js"></script>')},{path:"game/main.js",bytes:bytes("const score = 1;")},{path:"thumbnail.png",bytes:new Uint8Array([1,2,3])},{path:"metadata.json",bytes:bytes('{"author":"MathNexa"}')}];
async function fixture(){return {package_schema_version:"1.0",game_id:"fraction-field",version:"1.2.0",title:"Fraction Field",description:"Owner-created fraction game.",grade:4,topic:"Fractions",lesson:"Equivalent fractions",entry_file:"game/index.html",thumbnail:"thumbnail.png",asset_inventory:assets.map(a=>a.path),integrity_hashes:Object.fromEntries(await Promise.all(assets.map(async a=>[a.path,await hash(a.bytes)]))),minimum_mathnexa_runtime_version:"1.0.0"};}
describe("Phase 8E game package contract",()=>{
  it("accepts a complete exact manifest",async()=>expect(parseGamePackageManifest(await fixture())?.gameId).toBe("fraction-field"));
  it("rejects traversal, script hooks, and unknown manifest authority",async()=>{expect(normalizeGameAssetPath("../escape.js")).toBeNull();expect(parseGamePackageManifest({...await fixture(),scripts:{postinstall:"bad"}})).toBeNull();});
  it("accepts standalone packages without curriculum parents while preserving legacy discovery metadata",async()=>{const legacy=await fixture();const {grade: _grade,topic: _topic,lesson: _lesson,...standalone}=legacy;const parsed=parseGamePackageManifest(standalone);expect(parsed?.gameId).toBe("fraction-field");expect(parsed?.grade).toBeUndefined();expect(parseGamePackageManifest({...standalone,grade:4})).toBeNull();});
  it("compares package versions deterministically",()=>{expect(compareGamePackageVersions("1.2.0","1.1.9")).toBe(1);expect(compareGamePackageVersions("1.0.0-beta","1.0.0")).toBeNull();});
  it("verifies inventory hashes and permits only CSP-compatible content",async()=>expect((await inspectGamePackage({manifestJson:await fixture(),metadataJson:{author:"MathNexa"},assets})).decision).toBe("accepted"));
  it("quarantines checksum drift, dynamic code, and external network references",async()=>{const bad=assets.map(a=>a.path==="game/main.js"?{...a,bytes:bytes("eval('x'); fetch('https://bad.test')")}:a);const result=await inspectGamePackage({manifestJson:await fixture(),metadataJson:{author:"MathNexa"},assets:bad});expect(result.decision).toBe("quarantined");expect(result.findings.join(" ")).toMatch(/checksum-mismatch|dynamic-or-privileged|external-network/);});
});
