import{createHmac}from"node:crypto";import{expect,test}from"@playwright/test";import{createClient,type SupabaseClient,type User}from"@supabase/supabase-js";import sharp from"sharp";
const url=process.env.SUPABASE_TEST_URL??"",key=process.env.SUPABASE_TEST_SECRET_KEY??"",password="SyntheticAdmin42!",email=`phase8f-${Date.now()}-owner@example.test`;let admin:SupabaseClient,owner:User;
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const c of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(c).toString(2).padStart(5,"0");const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(Number.parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes)}function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest(),offset=digest.at(-1)!&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,"0")}
test.beforeAll(async()=>{expect(url).toBe("http://127.0.0.1:55321");admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const created=await admin.auth.admin.createUser({email,password,email_confirm:true});if(created.error||!created.data.user)throw created.error;owner=created.data.user;const row=await admin.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false});if(row.error)throw row.error});
test.afterAll(async()=>{if(owner)await admin.auth.admin.deleteUser(owner.id)});
test("owner validates media and publishes allowlisted CMS without retroactive legal edits",async({page,request})=>{await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);
  await page.goto("/admin?section=media-library");await page.getByLabel("Stable key").fill("learning-hero");await page.getByLabel("Alt text").fill("Colorful fraction tiles on a classroom table");await page.getByLabel("Caption").fill("Teacher-led fraction practice");await page.getByLabel("Attribution").fill("MathNexa");await page.getByLabel("License").fill("owned");const png=await sharp({create:{width:8,height:8,channels:4,background:{r:36,g:99,b:235,alpha:1}}}).png().toBuffer();await page.getByLabel("File").setInputFiles({name:"fraction-tiles.png",mimeType:"image/png",buffer:png});await page.getByRole("button",{name:"Validate and save private media"}).click();await expect(page).toHaveURL(/media=draft-saved/);await page.getByRole("button",{name:"Submit for review"}).click();await expect(page).toHaveURL(/media=state-updated/);await page.getByRole("button",{name:"Publish derivative"}).click();await expect(page).toHaveURL(/media=published/);const media=(await admin.from("cms_media_assets").select("id").eq("media_key","learning-hero").single()).data!;
  await page.goto("/admin?section=cms");const create=page.locator('form[action="/admin/cms/save"]').first();await create.locator('input[name="title"]').fill("Practice math with purpose");await create.locator('textarea[name="description"]').fill("Teacher-led, parent-friendly mathematics practice.");await create.locator('input[name="seoTitle"]').fill("MathNexa math practice");await create.locator('input[name="seoDescription"]').fill("Teacher-led math practice by grade, topic, and lesson.");await create.locator('input[name="socialTitle"]').fill("MathNexa");await create.locator('input[name="socialDescription"]').fill("Practice math with purpose.");await create.locator('textarea[name="blocks"]').fill(JSON.stringify([{type:"hero",heading:"Practice math with purpose",body:"Choose a reviewed activity.",mediaId:media.id}]));await create.getByRole("button",{name:"Validate and save draft"}).click();await expect(page).toHaveURL(/cms=draft-saved/);await page.getByRole("button",{name:"Submit for review"}).click();await expect(page).toHaveURL(/cms=state-updated/);await page.getByRole("button",{name:"Publish reviewed version"}).click();await expect(page).toHaveURL(/cms=published/);
  await page.goto("/");await expect(page.getByRole("heading",{name:"Practice math with purpose",level:1})).toBeVisible();const image=page.getByRole("img",{name:"Colorful fraction tiles on a classroom table"});await expect(image).toBeVisible();expect((await request.get(await image.getAttribute("src")??"")).status()).toBe(200);
  await page.goto("/admin?section=cms");const legalForm=page.locator('form[action="/admin/cms/save"]').first();await legalForm.locator('select[name="key"]').selectOption("terms");await legalForm.locator('input[name="title"]').fill("MathNexa terms");await legalForm.locator('textarea[name="blocks"]').fill('[{"type":"legal-section","heading":"Access","body":"Reviewed prospective terms."}]');await legalForm.getByRole("button",{name:"Validate and save draft"}).click();await expect(page).toHaveURL(/cms=draft-saved/);const cards=page.locator(".admin-library-list article");const terms=cards.filter({hasText:"terms"});await terms.getByRole("button",{name:"Submit for review"}).click();await terms.getByRole("button",{name:"Publish reviewed version"}).click();await page.goto("/terms");await expect(page.getByRole("heading",{name:"MathNexa terms",level:1})).toBeVisible();expect(await page.locator("[data-cms-version='1']").count()).toBe(1);
  expect((await admin.from("cms_media_usage").select("media_asset_id",{count:"exact",head:true}).eq("media_asset_id",media.id)).count).toBe(1);expect((await admin.from("admin_audit_log").select("id",{count:"exact",head:true}).like("action","admin.cms.%")).count).toBeGreaterThanOrEqual(6);
});
