import {createHash,createHmac,randomUUID} from "node:crypto";
import {expect,request as playwrightRequest,test} from "@playwright/test";
// Admin-preview tickets: the v1 wire format, signed with the local delivery secret (lib/games/ticket.ts).
const deliverySecret=process.env.MVH_GAME_DELIVERY_SECRET??"";
function mintTicket({aud,packageId,principalId,issuedAt=Math.floor(Date.now()/1000),lifetime=300}:{aud:string;packageId:string;principalId:string;issuedAt?:number;lifetime?:number}){const encoded=Buffer.from(JSON.stringify({v:1,aud,packageId,principalId,issuedAt,expiresAt:issuedAt+lifetime})).toString("base64url");return `${encoded}.${createHmac("sha256",deliverySecret).update(encoded).digest("base64url")}`}
function flipTicket(ticket:string){const[payload,mac]=ticket.split(".") as [string,string];return `${payload}.${mac.slice(0,10)}${mac[10]==="A"?"B":"A"}${mac.slice(11)}`}
import {createClient,type SupabaseClient,type User}from"@supabase/supabase-js";
import{zipSync}from"fflate";
const url=process.env.SUPABASE_TEST_URL??"",key=process.env.SUPABASE_TEST_SECRET_KEY??"",password="SyntheticAdmin42!",email="phase8e-browser-owner@example.test";let admin:SupabaseClient,owner:User,adminId="";
const bytes=(value:string)=>Uint8Array.from(Buffer.from(value));const sha=(value:Uint8Array)=>createHash("sha256").update(value).digest("hex");
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const character of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(character).toString(2).padStart(5,"0");const result=[];for(let offset=0;offset+8<=bits.length;offset+=8)result.push(Number.parseInt(bits.slice(offset,offset+8),2));return Buffer.from(result)}
function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest(),offset=digest.at(-1)!&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,"0")}
function archive(unsafe=false){const assets={"game/index.html":bytes('<!doctype html><html><head><link rel="stylesheet" href="styles.css"><script src="main.js" defer></script></head><body><main><h1>Fraction Field</h1><button id="answer">Show answer</button><output id="result"></output></main></body></html>'),"game/main.js":bytes(unsafe?'eval("bad")':'document.querySelector("#answer").addEventListener("click",()=>{document.querySelector("#result").textContent="Equivalent fractions match"})'),"game/styles.css":bytes("body{font-family:system-ui;background:#fff;color:#102a43}button{min-height:44px}"),"thumbnail.png":Uint8Array.from([137,80,78,71,13,10,26,10]),"metadata.json":bytes('{"author":"MathNexa","generator":"Codex"}')};const manifest={package_schema_version:"1.0",game_id:unsafe?"unsafe-fraction-field":"phase8e-fraction-field",version:"1.0.0",title:unsafe?"Unsafe Fraction Field":"Fraction Field",description:"Owner-created equivalent fractions game.",entry_file:"game/index.html",thumbnail:"thumbnail.png",asset_inventory:Object.keys(assets),integrity_hashes:Object.fromEntries(Object.entries(assets).map(([path,value])=>[path,sha(value)])),minimum_mathnexa_runtime_version:"1.0.0"};return Buffer.from(zipSync({"manifest.json":bytes(JSON.stringify(manifest)),...assets},{level:6}))}
async function fillGameForm(page:import("@playwright/test").Page,title:string,slug:string,order:string){const form=page.locator("#add-games form");await form.getByLabel("Title",{exact:true}).fill(title);await form.getByLabel("Slug",{exact:true}).fill(slug);await form.getByLabel("Description").fill("Owner-created equivalent fractions game.");await form.getByLabel("Display order").fill(order);return form}
test.beforeAll(async()=>{expect(url).toBe("http://127.0.0.1:55321");admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const created=await admin.auth.admin.createUser({email,password,email_confirm:true});if(created.error||!created.data.user)throw created.error;owner=created.data.user;const row=await admin.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false}).select("id").single();if(row.error)throw row.error;adminId=row.data.id;});
test("owner validates, previews, publishes, and quarantines package ZIPs",async({page,request})=>{await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(email);await page.locator("input[name=\"password\"]").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);
await page.goto("/admin?section=games");let form=await fillGameForm(page,"Fraction Field","phase8e-fraction-field","20");await form.getByLabel("MathNexa ZIP package").setInputFiles({name:"fraction-field.zip",mimeType:"application/zip",buffer:archive()});await form.getByRole("button",{name:"Upload and validate package"}).click();await expect(page).toHaveURL(/package=saved/);await expect(page.getByText("Package draft imported.")).toBeVisible();let gameCard=page.locator("article").filter({has:page.getByRole("heading",{name:"Fraction Field",exact:true})});const previewHref=await gameCard.getByRole("link",{name:"Preview"}).getAttribute("href");expect(previewHref).toMatch(/^\/admin\/games\/[0-9a-f-]{36}\/preview$/);await page.goto(previewHref!);const frame=page.frameLocator("iframe");await expect(frame.getByRole("heading",{name:"Fraction Field"})).toBeVisible();await frame.getByRole("button",{name:"Show answer"}).click();await expect(frame.getByText("Equivalent fractions match")).toBeVisible();
/* The Admin preview stays a script-only sandbox fed by ticket-only, 300-second admin-preview assets. */await expect(page.locator("iframe")).toHaveAttribute("sandbox","allow-scripts");const previewSrc=(await page.locator("iframe").getAttribute("src"))??"",previewMatch=/^\/admin\/games\/([0-9a-f-]{36})\/preview\/assets\/([A-Za-z0-9_-]+\.[A-Za-z0-9_-]{43})\/game\/index\.html$/.exec(previewSrc);expect(previewMatch,"admin preview frame source").not.toBeNull();const previewId=previewMatch![1]!,adminTicket=previewMatch![2]!,adminPayload=JSON.parse(Buffer.from(adminTicket.split(".")[0]!,"base64url").toString("utf8"));expect(Object.keys(adminPayload).sort()).toEqual(["aud","expiresAt","issuedAt","packageId","principalId","v"]);expect(adminPayload).toMatchObject({v:1,aud:"admin-preview",packageId:previewId});expect(adminPayload.expiresAt-adminPayload.issuedAt).toBe(300);
const anonPreview=await playwrightRequest.newContext({baseURL:"http://127.0.0.1:3000"}),previewAsset=(ticket:string,file:string,id=previewId)=>`/admin/games/${id}/preview/assets/${ticket}/${file}`;expect((await anonPreview.get(previewAsset(adminTicket,"game/styles.css"))).status()).toBe(200);expect((await anonPreview.get(previewAsset(adminTicket,"game/main.js"))).status()).toBe(200);expect((await anonPreview.get(previewAsset(adminTicket,"game/index.html"),{headers:{"Sec-Fetch-Dest":"iframe"}})).status()).toBe(200);expect((await anonPreview.get(previewAsset(mintTicket({aud:"admin-preview",packageId:previewId,principalId:adminPayload.principalId}),"game/styles.css"))).status(),"a re-minted admin-preview ticket (the format is reproduced)").toBe(200);
for(const[label,forged]of[["subscriber audience",mintTicket({aud:"subscriber",packageId:previewId,principalId:randomUUID()})],["lifetime 301",mintTicket({aud:"admin-preview",packageId:previewId,principalId:adminPayload.principalId,lifetime:301})],["expired",mintTicket({aud:"admin-preview",packageId:previewId,principalId:adminPayload.principalId,issuedAt:Math.floor(Date.now()/1000)-301})],["another package",mintTicket({aud:"admin-preview",packageId:randomUUID(),principalId:adminPayload.principalId})],["flipped MAC",flipTicket(adminTicket)]] as const)expect((await anonPreview.get(previewAsset(forged,"game/styles.css"))).status(),label).toBe(404);await anonPreview.dispose();const packageRow=await admin.from("game_packages").select("id,entry_file").eq("game_id","phase8e-fraction-field").single();if(packageRow.error)throw packageRow.error;expect((await page.request.get(`/admin/games/${packageRow.data.id}/preview/${packageRow.data.entry_file}`)).status()).toBe(404);
await page.goto("/admin?section=games");gameCard=page.locator("article").filter({has:page.getByRole("heading",{name:"Fraction Field",exact:true})});for(const label of ["Validate package","Mark ready for review","Publish game"]){await gameCard.getByRole("button",{name:label,exact:true}).click();await expect(page).toHaveURL(/package=updated/);gameCard=page.locator("article").filter({has:page.getByRole("heading",{name:"Fraction Field",exact:true})})}const published=await admin.from("game_packages").select("publication_state").eq("id",packageRow.data.id).single();expect(published.error).toBeNull();expect(published.data?.publication_state).toBe("published");await page.goto("/games");await expect(page).toHaveURL(/\/access\?next=\/games$/);await expect(page.getByRole("heading",{name:"Continue to Math Games",level:1,exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Fraction Field"})).toHaveCount(0);
await page.goto("/admin?section=games");form=await fillGameForm(page,"Unsafe Fraction Field","unsafe-fraction-field","21");await form.getByLabel("MathNexa ZIP package").setInputFiles({name:"unsafe-fraction-field.zip",mimeType:"application/zip",buffer:archive(true)});await form.getByRole("button",{name:"Upload and validate package"}).click();await expect(page).toHaveURL(/package=quarantined/);await expect(page.getByText("Unsafe package quarantined.")).toBeVisible();expect((await admin.from("game_package_quarantine_events").select("id",{count:"exact",head:true})).count).toBe(1);expect((await admin.from("game_packages").select("id",{count:"exact",head:true}).eq("game_id","unsafe-fraction-field")).count).toBe(0);});
