import {createHash,createHmac} from "node:crypto";
import {expect,test} from "@playwright/test";
import {createClient,type SupabaseClient,type User}from"@supabase/supabase-js";
import{zipSync}from"fflate";
const url=process.env.SUPABASE_TEST_URL??"",key=process.env.SUPABASE_TEST_SECRET_KEY??"",password="SyntheticAdmin42!",email="phase8e-browser-owner@example.test";let admin:SupabaseClient,owner:User,adminId="";
const bytes=(value:string)=>Uint8Array.from(Buffer.from(value));const sha=(value:Uint8Array)=>createHash("sha256").update(value).digest("hex");
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const character of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(character).toString(2).padStart(5,"0");const result=[];for(let offset=0;offset+8<=bits.length;offset+=8)result.push(Number.parseInt(bits.slice(offset,offset+8),2));return Buffer.from(result)}
function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest(),offset=digest.at(-1)!&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,"0")}
function archive(unsafe=false){const assets={"game/index.html":bytes('<!doctype html><html><head><link rel="stylesheet" href="styles.css"><script src="main.js" defer></script></head><body><main><h1>Fraction Field</h1><button id="answer">Show answer</button><output id="result"></output></main></body></html>'),"game/main.js":bytes(unsafe?'eval("bad")':'document.querySelector("#answer").addEventListener("click",()=>{document.querySelector("#result").textContent="Equivalent fractions match"})'),"game/styles.css":bytes("body{font-family:system-ui;background:#fff;color:#102a43}button{min-height:44px}"),"thumbnail.png":Uint8Array.from([137,80,78,71,13,10,26,10]),"metadata.json":bytes('{"author":"MathNexa","generator":"Codex"}')};const manifest={package_schema_version:"1.0",game_id:unsafe?"unsafe-fraction-field":"phase8e-fraction-field",version:"1.0.0",title:unsafe?"Unsafe Fraction Field":"Fraction Field",description:"Owner-created equivalent fractions game.",grade:4,topic:"Fractions",lesson:"Equivalent fractions",entry_file:"game/index.html",thumbnail:"thumbnail.png",asset_inventory:Object.keys(assets),integrity_hashes:Object.fromEntries(Object.entries(assets).map(([path,value])=>[path,sha(value)])),minimum_mathnexa_runtime_version:"1.0.0"};return Buffer.from(zipSync({"manifest.json":bytes(JSON.stringify(manifest)),...assets},{level:6}))}
test.beforeAll(async()=>{expect(url).toBe("http://127.0.0.1:55321");admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const created=await admin.auth.admin.createUser({email,password,email_confirm:true});if(created.error||!created.data.user)throw created.error;owner=created.data.user;const row=await admin.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false}).select("id").single();if(row.error)throw row.error;adminId=row.data.id;});
test("owner validates, previews, publishes, and quarantines package ZIPs",async({page,request})=>{await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);
const grade=await admin.rpc("create_content_grade",{p_actor_admin_id:adminId,p_grade_number:4,p_title:"Grade 4",p_slug:"grade-4",p_sort_order:4});if(grade.error)throw grade.error;const topic=await admin.rpc("create_content_topic",{p_actor_admin_id:adminId,p_grade_id:grade.data,p_title:"Fractions",p_slug:"fractions",p_sort_order:1});if(topic.error)throw topic.error;const lesson=await admin.rpc("create_content_lesson",{p_actor_admin_id:adminId,p_topic_id:topic.data,p_title:"Equivalent fractions",p_slug:"equivalent-fractions",p_sort_order:1});if(lesson.error)throw lesson.error;
await page.goto("/admin?section=games");await page.getByLabel("MathNexa ZIP package").setInputFiles({name:"fraction-field.zip",mimeType:"application/zip",buffer:archive()});await page.getByRole("button",{name:"Upload and validate package"}).click();await expect(page).toHaveURL(/package=saved/);await expect(page.getByText("Package draft imported.")).toBeVisible();const previewHref=await page.getByRole("link",{name:"Preview sandbox"}).getAttribute("href");expect(previewHref).toMatch(/^\/admin\/games\/[0-9a-f-]{36}\/preview$/);await page.goto(previewHref!);const frame=page.frameLocator("iframe");await expect(frame.getByRole("heading",{name:"Fraction Field"})).toBeVisible();await frame.getByRole("button",{name:"Show answer"}).click();await expect(frame.getByText("Equivalent fractions match")).toBeVisible();const packageRow=await admin.from("game_packages").select("id,entry_file").eq("game_id","phase8e-fraction-field").single();if(packageRow.error)throw packageRow.error;expect((await page.request.get(`/admin/games/${packageRow.data.id}/preview/${packageRow.data.entry_file}`)).status()).toBe(404);
await page.goto("/admin?section=games");for(const label of ["Validate package","Mark ready for review","Publish game"]){await page.getByRole("button",{name:label,exact:true}).click();await expect(page).toHaveURL(/package=updated/)}const published=await admin.from("game_packages").select("publication_state").eq("id",packageRow.data.id).single();expect(published.error).toBeNull();expect(published.data?.publication_state).toBe("published");await page.goto("/games");await expect(page).toHaveURL(/\/access\?next=\/games$/);await expect(page.getByRole("heading",{name:"Continue to Games"})).toBeVisible();await expect(page.getByRole("heading",{name:"Fraction Field"})).toHaveCount(0);
await page.goto("/admin?section=games");await page.getByLabel("MathNexa ZIP package").setInputFiles({name:"unsafe-fraction-field.zip",mimeType:"application/zip",buffer:archive(true)});await page.getByRole("button",{name:"Upload and validate package"}).click();await expect(page).toHaveURL(/package=quarantined/);await expect(page.getByText("Unsafe package quarantined.")).toBeVisible();expect((await admin.from("game_package_quarantine_events").select("id",{count:"exact",head:true})).count).toBe(1);expect((await admin.from("game_packages").select("id",{count:"exact",head:true}).eq("game_id","unsafe-fraction-field")).count).toBe(0);});
