import { createHmac } from "node:crypto";
import { expect, test } from "@playwright/test";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";

const url=process.env.SUPABASE_TEST_URL??"",secretKey=process.env.SUPABASE_TEST_SECRET_KEY??"",password="SyntheticAdmin42!";
const run=`phase8g-${Date.now()}-${Math.random().toString(16).slice(2,8)}`,ownerEmail=`${run}-owner@example.test`,accountEmail=`${run}-account@example.test`;
let client:SupabaseClient,owner:User,account:User;
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const c of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(c).toString(2).padStart(5,"0");const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(Number.parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes)}
function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest(),offset=digest.at(-1)!&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1_000_000).padStart(6,"0")}

test.beforeAll(async()=>{expect(url).toBe("http://127.0.0.1:55321");client=createClient(url,secretKey,{auth:{autoRefreshToken:false,persistSession:false}});const model=await client.rpc("set_platform_identity_model",{p_identity_model:"consumer-v1"});if(model.error)throw model.error;const o=await client.auth.admin.createUser({email:ownerEmail,password,email_confirm:true}),a=await client.auth.admin.createUser({email:accountEmail,password,email_confirm:true});if(o.error||!o.data.user)throw o.error;if(a.error||!a.data.user)throw a.error;owner=o.data.user;account=a.data.user;const inserted=await client.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false});if(inserted.error)throw inserted.error});
test.afterAll(async()=>{if(account)await client.auth.admin.deleteUser(account.id);if(owner)await client.auth.admin.deleteUser(owner.id);await client.rpc("set_platform_identity_model",{p_identity_model:"legacy-preview"})});

test("owner uses bounded account operations while destructive workflows remain read-only",async({page})=>{
  await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(ownerEmail);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);
  await page.getByRole("link",{name:/Users/}).click();await expect(page).toHaveURL(/section=users/);const card=page.locator(".admin-account-card").filter({hasText:accountEmail});await expect(card).toBeVisible();await expect(card).toContainText(account.id);await expect(card).toContainText("none recorded");await expect(card.getByText("Refund approval:")).toBeVisible();await expect(card.getByText("Permanent deletion:")).toBeVisible();await expect(card.locator('input[type="password"]')).toHaveCount(0);
  const grant=card.getByRole("button",{name:"Grant complimentary access"});await grant.focus();await page.keyboard.press("Enter");let dialog=page.getByRole("dialog",{name:"Grant complimentary access"});await expect(dialog).toBeVisible();await expect(dialog.getByLabel("Required reason")).toBeFocused();await dialog.getByLabel("Required reason").fill("Approved local owner support walkthrough");await dialog.getByLabel(/I confirm the named account/).check();await dialog.getByRole("button",{name:"Confirm grant complimentary access"}).click();await expect(page).toHaveURL(/account=grant-complimentary-succeeded/);expect((await client.from("consumer_complimentary_entitlements").select("id",{count:"exact",head:true}).eq("owner_user_id",account.id).is("revoked_at",null)).count).toBe(1);
  const refreshed=page.locator(".admin-account-card").filter({hasText:accountEmail});await refreshed.getByRole("button",{name:"Suspend account"}).click();dialog=page.getByRole("dialog",{name:"Suspend account"});await dialog.getByLabel("Required reason").fill("Verified account access safety review");await dialog.getByLabel(/I confirm the named account/).check();await dialog.getByRole("button",{name:"Confirm suspend account"}).click();await expect(page).toHaveURL(/account=suspend-succeeded/);expect((await client.from("consumer_accounts").select("account_status").eq("user_id",account.id).single()).data?.account_status).toBe("suspended");const evidence=await client.from("admin_account_operations").select("operation_state,before_snapshot,after_snapshot").eq("target_user_id",account.id).eq("operation","suspend").single();expect(evidence.data?.operation_state).toBe("succeeded");expect(evidence.data?.before_snapshot.account_status).toBe("active");expect(evidence.data?.after_snapshot.account_status).toBe("suspended");
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce",forcedColors:"active"});await expect(page.locator(".admin-account-card").filter({hasText:accountEmail})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
});
