import { createHmac } from "node:crypto";
import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";

const url=process.env.SUPABASE_TEST_URL??"",secretKey=process.env.SUPABASE_TEST_SECRET_KEY??"",password="SyntheticAdmin42!";
const run=`phase8h-${Date.now()}-${Math.random().toString(16).slice(2,8)}`,ownerEmail=`${run}-owner@example.test`;
let client:SupabaseClient,owner:User;
function base32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="";for(const c of value.replaceAll("=","").toUpperCase())bits+=alphabet.indexOf(c).toString(2).padStart(5,"0");const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(Number.parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes)}
function totp(secret:string){const payload=Buffer.alloc(8);payload.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",base32(secret)).update(payload).digest(),offset=digest.at(-1)!&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1_000_000).padStart(6,"0")}

test.beforeAll(async()=>{expect(url).toBe("http://127.0.0.1:55321");client=createClient(url,secretKey,{auth:{autoRefreshToken:false,persistSession:false}});const model=await client.rpc("set_platform_identity_model",{p_identity_model:"consumer-v1"});if(model.error)throw model.error;const created=await client.auth.admin.createUser({email:ownerEmail,password,email_confirm:true});if(created.error||!created.data.user)throw created.error;owner=created.data.user;const inserted=await client.from("admin_users").insert({user_id:owner.id,role:"owner",mfa_enrolled:false});if(inserted.error)throw inserted.error});
test.afterAll(async()=>{if(owner)await client.auth.admin.deleteUser(owner.id);await client.rpc("set_platform_identity_model",{p_identity_model:"legacy-preview"})});

test("owner reviews aggregate analytics and audited server operations without identity leakage",async({page})=>{
  await page.goto("/admin/sign-in");await page.getByLabel("Owner email address").fill(ownerEmail);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Continue securely"}).click();await page.getByRole("button",{name:"Set up authenticator"}).click();const secret=(await page.locator("code.admin-setup-secret").textContent())?.trim()??"";await page.getByLabel("Six-digit authenticator code").fill(totp(secret));await page.getByRole("button",{name:"Verify and open admin"}).click();await expect(page).toHaveURL(/\/admin$/);

  await page.getByRole("link",{name:/Analytics/}).click();await expect(page.getByRole("heading",{name:"Aggregate analytics"})).toBeVisible();await expect(page.getByText("Account growth",{exact:true})).toBeVisible();await expect(page.getByText("Game completions",{exact:true})).toBeVisible();await expect(page.getByText(/No completion signal is currently available/)).toBeVisible();await expect(page.getByText(/No connected Vercel error feed/)).toBeVisible();await expect(page.getByText(/ShowMe Math/i)).toHaveCount(0);
  const downloadPromise=page.waitForEvent("download");await page.getByRole("link",{name:"Export aggregate CSV"}).click();const download=await downloadPromise;const body=await readFile(await download.path()??"","utf8");expect(body).toContain("account-growth");expect(body).not.toContain(ownerEmail);expect(body).not.toMatch(/consumer_user_id|owner_user_id|token|cookie|password/i);

  await page.getByRole("link",{name:/Settings/}).click();await expect(page.getByRole("heading",{name:"System health and controls"})).toBeVisible();await expect(page.getByText(/^(?:phase8h-local|[0-9a-f]{40})$/)).toBeVisible();const maintenance=page.locator(".admin-flag-grid article").filter({hasText:"maintenance mode"});await maintenance.getByLabel("Public-safe message").fill("Brief local maintenance verification");await maintenance.getByLabel("Required reason").fill("Local Phase 8H owner verification");await maintenance.getByRole("button",{name:"Enable maintenance mode"}).click();await expect(page).toHaveURL(/ops=flag-updated/);expect((await client.from("platform_feature_flags").select("enabled").eq("flag_key","maintenance-mode").single()).data?.enabled).toBe(true);
  await page.goto("/");await expect(page.getByRole("alert")).toContainText("Brief local maintenance verification");await page.goto("/admin?section=settings");const enabledMaintenance=page.locator(".admin-flag-grid article").filter({hasText:"maintenance mode"});await enabledMaintenance.getByLabel("Required reason").fill("Local verification complete");await enabledMaintenance.getByRole("button",{name:"Disable maintenance mode"}).click();expect((await client.from("platform_feature_flags").select("enabled").eq("flag_key","maintenance-mode").single()).data?.enabled).toBe(false);

  await page.getByRole("link",{name:/Audit Log/}).click();await expect(page.getByRole("heading",{name:"Audit log"})).toBeVisible();await expect(page.getByText("admin.operations.feature-flag.changed").first()).toBeVisible();await expect(page.getByRole("link",{name:"Export sanitized audit CSV"})).toBeVisible();
  await page.getByRole("link",{name:/Settings/}).click();await expect(page.getByRole("button",{name:"Enable admin emergency disabled"})).toBeVisible();await expect(page.getByText(/deletes only aggregate signals older than 400 days/)).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce",forcedColors:"active"});await expect(page.getByRole("heading",{name:"System health and controls"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
});
