drop trigger if exists content_resource_version_require_game on public.content_resource_versions;
drop function if exists private.require_game_package_before_publish();
drop function if exists public.record_game_package_launch(uuid,uuid);
drop function if exists public.rollback_game_package(uuid,uuid,bigint);
drop function if exists public.archive_game_package(uuid,uuid,bigint);
drop function if exists public.transition_game_package(uuid,uuid,bigint,text);
drop function if exists public.record_game_package_quarantine(uuid,text,text,bigint,text,jsonb);
drop function if exists public.register_game_package(uuid,uuid,integer,text,text,text,text,text,text,jsonb,jsonb,text,bigint,bigint,jsonb);
drop function if exists private.game_version_parts(text);
drop table if exists public.game_launch_events;
drop table if exists public.game_package_quarantine_events;
drop table if exists public.game_package_assets;
drop table if exists public.game_packages;
drop policy if exists game_package_objects_server_only_delete on storage.objects;
drop policy if exists game_package_objects_server_only_update on storage.objects;
drop policy if exists game_package_objects_server_only_insert on storage.objects;
drop policy if exists game_package_objects_server_only_select on storage.objects;
drop policy if exists game_package_buckets_hide_from_browser on storage.buckets;
delete from storage.buckets where id in ('game-packages','game-package-quarantine') and not exists(select 1 from storage.objects where bucket_id=storage.buckets.id);
