import { describe, expect, it } from "vitest";

import * as platformCore from "./index.js";

describe("platform-core public API", () => {
  it("exposes the intentional runtime contract surface", () => {
    expect(Object.keys(platformCore).sort()).toEqual([
      "BILLING_CATALOG",
      "BILLING_PLAN_KEYS",
      "BILLING_SUBSCRIPTION_STATUSES",
      "BILLING_UI_COPY",
      "BILLING_UI_STATES",
      "AUTH_EMAIL_DELIVERY_STATES",
      "CAPABILITIES_BY_KEY",
      "CAPABILITY_DECISION_REASONS",
      "CAPABILITY_KEYS",
      "CAPABILITY_REGISTRY",
      "CONTROLLED_PILOT_STATES",
      "CLASS_GRADES",
      "CURRICULUM_STATUSES",
      "DELETION_STATES",
      "FEATURE_KEYS",
      "GAME_ENTITLEMENT_STATES",
      "OBSERVABILITY_CATEGORIES",
      "PILOT_CHECKLIST_KEYS",
      "PILOT_ACTIVATION_PREREQUISITES",
      "PILOT_EVENT_CODES",
      "PILOT_READINESS_STATES",
      "PLATFORM_ENVIRONMENTS",
      "PRODUCT_CATALOG",
      "PRODUCT_KEYS",
      "PRODUCT_PACKAGES",
      "SESSION_STATUSES",
      "assertUniqueKeys",
      "canTransitionDeletion",
      "createEmptyPilotChecklist",
      "createIncompletePilotPrerequisites",
      "createEntitlementPolicy",
      "createPilotEvent",
      "createSafeEvent",
      "createSyntheticPilotFixture",
      "decideCapability",
      "decideGameAccess",
      "defineBillingCatalog",
      "defineCapabilityRegistry",
      "defineProductCatalog",
      "denyTeacherOperation",
      "deriveBillingEntitlement",
      "evaluatePilotPolicy",
      "evaluatePilotActivation",
      "evaluatePilotReadiness",
      "getProductPackage",
      "isBillingPlanKey",
      "isCapabilityKey",
      "isFeatureKey",
      "isTrialEligible",
      "isTransactionalAuthEmailVerified",
      "isProductKey",
      "normalizeBillingSubscriptionStatus",
      "parseActivityDefinition",
      "parseAggregateReport",
      "parseBillingPlanKey",
      "parseCapabilityDefinition",
      "parseCapabilityKey",
      "parseClassRecord",
      "parseCurriculumSummary",
      "parseEntitlement",
      "parseEnvironmentRegistry",
      "parseAuthEmailDeliveryState",
      "parseFeatureKey",
      "parseGameEntitlementEvidence",
      "parsePilotCorrelationId",
      "parseProductKey",
      "parseSessionRecord",
      "parseTeacherDashboard",
      "parseTeacherProfile",
      "parseUserId",
      "planDeletion",
      "renderEmailTemplate",
      "teacherFailure",
      "teacherSuccess",
      "verifySyntheticFixtureCleanup"
    ].sort());
  });

  it("preserves default-deny guards through the package entry point", () => {
    expect(platformCore.isProductKey("math-vocabulary-hunt")).toBe(true);
    expect(platformCore.isProductKey("premium=true")).toBe(false);
    expect(platformCore.isFeatureKey("premium-game-modes")).toBe(true);
    expect(platformCore.isFeatureKey("everything")).toBe(false);
  });
});
