import {createHash,randomUUID}from"node:crypto";import sharp from"sharp";import{inspectImageUpload,inspectPdfUpload,parseMediaMetadata}from"@math-vocabulary-hunt/platform-core";import{NextResponse}from"next/server";import{inspectAdminAccess,validateAdminMutationCsrf}from"@/lib/admin/session";import{createServiceSupabaseClient}from"@/lib/supabase/service";
export const runtime="nodejs";function v(f:FormData,n:string){return String(f.get(n)??"").trim()}function back(r:Request,s:string){const u=new URL("/admin",process.env.MVH_APPLICATION_ORIGIN??r.url);u.searchParams.set("section","media-library");u.searchParams.set("media",s);return NextResponse.redirect(u,303)}
function audioMime(bytes:Uint8Array,claimed:string){const ascii=new TextDecoder("ascii").decode(bytes.slice(0,12));if((bytes[0]===0x49&&bytes[1]===0x44&&bytes[2]===0x33)||(bytes[0]===0xff&&(bytes[1]&0xe0)===0xe0))return claimed==="audio/mpeg"?claimed:null;if(ascii.startsWith("OggS"))return claimed==="audio/ogg"?claimed:null;if(ascii.startsWith("RIFF")&&ascii.slice(8)==="WAVE")return claimed==="audio/wav"?claimed:null;return null}
export async function POST(r:Request){const a=await inspectAdminAccess();if(a.state!=="authorized")return new NextResponse("Not Found",{status:404});const f=await r.formData();if(!await validateAdminMutationCsrf(f))return back(r,"csrf-denied");const upload=f.get("media");const key=v(f,"key"),metadata=parseMediaMetadata({kind:v(f,"kind"),altText:v(f,"altText"),caption:v(f,"caption"),attribution:v(f,"attribution"),license:v(f,"license")});if(!(upload instanceof File)||upload.size<16||upload.size>20*1024*1024||!metadata||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(key))return back(r,"invalid-input");
  const replacement=v(f,"replace").split("|");const replacementId=replacement[0]||null,replacementLock=Number(replacement[1]),nextVersion=replacementId?Number(replacement[2])+1:1;if(replacementId&&(!/^[0-9a-f-]{36}$/i.test(replacementId)||!Number.isSafeInteger(replacementLock)||!Number.isSafeInteger(nextVersion)))return back(r,"invalid-input");
  const client=createServiceSupabaseClient();if(!client)return back(r,"failed-closed");if(replacementId){const target=await client.from("cms_media_assets").select("media_key,media_kind,lock_version,current_version_number").eq("id",replacementId).maybeSingle();if(target.error||!target.data||target.data.media_key!==key||target.data.media_kind!==metadata.kind||Number(target.data.lock_version)!==replacementLock||Number(target.data.current_version_number)+1!==nextVersion)return back(r,"failed-closed")};const bytes=new Uint8Array(await upload.arrayBuffer());let accepted=false,mime="application/octet-stream",derivative:Uint8Array|null=null,derivativeMime:string|null=null,width:number|null=null,height:number|null=null,findings:unknown[]=[];
  try{if(["image","icon","logo","thumbnail","preview-image"].includes(metadata.kind)){const i=inspectImageUpload({filename:upload.name,mimeType:upload.type,bytes});accepted=i.decision==="accepted";findings=[...i.findings];mime=i.mimeType??"application/octet-stream";if(accepted){const output=await sharp(bytes,{failOn:"warning",limitInputPixels:8192*8192}).rotate().resize({width:2048,height:2048,fit:"inside",withoutEnlargement:true}).webp({quality:82}).toBuffer({resolveWithObject:true});derivative=new Uint8Array(output.data);derivativeMime="image/webp";width=output.info.width;height=output.info.height}}
    else if(metadata.kind==="downloadable-pdf"){const p=inspectPdfUpload({filename:upload.name,mimeType:upload.type,bytes});accepted=p.decision==="accepted";findings=[...p.findings];mime=accepted?"application/pdf":"application/octet-stream";if(accepted){derivative=bytes;derivativeMime="application/pdf"}}
    else if(metadata.kind==="audio"){const detected=audioMime(bytes,upload.type);accepted=detected!==null;mime=detected??"application/octet-stream";findings=accepted?[]:["audio-magic-mismatch"];if(accepted){derivative=bytes;derivativeMime=mime}}}catch{accepted=false;findings=["media-decoder-rejected"]}
  const id=replacementId??randomUUID(),safeName=upload.name.toLowerCase().replace(/[^a-z0-9.]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120)||"upload.bin";const originalPath=`${accepted?"originals":"quarantine"}/${id}/v${nextVersion}/${safeName}`,derivativePath=accepted?`derivatives/${id}/v${nextVersion}/${metadata.kind.includes("image")||["icon","logo","thumbnail","preview-image"].includes(metadata.kind)?"optimized.webp":safeName}`:null;const bucket=accepted?"cms-media":"cms-media-quarantine";
  const original=await client.storage.from(bucket).upload(originalPath,bytes,{contentType:accepted?mime:"application/octet-stream",upsert:false,cacheControl:"private, max-age=0"});if(original.error)return back(r,"failed-closed");if(accepted&&derivative&&derivativePath){const stored=await client.storage.from(bucket).upload(derivativePath,derivative,{contentType:derivativeMime!,upsert:false,cacheControl:"public, max-age=31536000, immutable"});if(stored.error){await client.storage.from(bucket).remove([originalPath]);return back(r,"failed-closed")}}
  const common={p_actor_admin_id:a.admin.id,p_original_filename:upload.name.slice(0,255),p_bucket_id:bucket,p_original_path:originalPath,p_derivative_path:derivativePath,p_mime_type:mime,p_derivative_mime_type:derivativeMime,p_byte_size:bytes.byteLength,p_sha256:createHash("sha256").update(bytes).digest("hex"),p_width:width,p_height:height,p_alt_text:metadata.altText,p_caption:metadata.caption,p_attribution:metadata.attribution,p_license:metadata.license,p_validation_state:accepted?"accepted":"quarantined",p_validation_report:{validator:"phase8f-media-v1",findings,optimized:accepted&&derivativeMime==="image/webp"}};const registered=replacementId?await client.rpc("revise_cms_media",{...common,p_media_asset_id:replacementId,p_expected_lock_version:replacementLock}):await client.rpc("register_cms_media",{...common,p_media_key:key,p_media_kind:metadata.kind});if(registered.error){await client.storage.from(bucket).remove([originalPath,...(derivativePath?[derivativePath]:[])]);return back(r,"failed-closed")}return back(r,accepted?(replacementId?"revision-saved":"draft-saved"):"quarantined")}
