import{createHash,randomUUID}from"node:crypto";
import{compareGamePackageVersions}from"@math-vocabulary-hunt/platform-core";
import{NextResponse}from"next/server";
import{inspectGameArchive,normalizeGamePackageFilename}from"@/lib/admin/game-package-import";
import{inspectAdminAccess,validateAdminMutationCsrf}from"@/lib/admin/session";
import{createServiceSupabaseClient}from"@/lib/supabase/service";
export const runtime="nodejs";
const redirectResult=(request:Request,result:string)=>{const url=new URL("/admin",process.env.MVH_APPLICATION_ORIGIN??request.url);url.searchParams.set("section","games");url.searchParams.set("package",result);return NextResponse.redirect(url,303)};
const value=(form:FormData,name:string)=>String(form.get(name)??"").trim();
export async function POST(request:Request){
  const access=await inspectAdminAccess();if(access.state!=="authorized")return new NextResponse("Not Found",{status:404});const form=await request.formData();if(!await validateAdminMutationCsrf(form))return redirectResult(request,"csrf-denied");
  const lessonId=value(form,"lessonId"),sortOrder=Number(value(form,"sortOrder")),upload=form.get("gamePackage");if(!(upload instanceof File)||!upload.size||upload.size>25*1024*1024||!Number.isSafeInteger(sortOrder)||sortOrder<1||sortOrder>32767||!/^[0-9a-f-]{36}$/i.test(lessonId))return redirectResult(request,"invalid-input");
  const normalized=normalizeGamePackageFilename(upload.name);if(!normalized||!["application/zip","application/x-zip-compressed","application/octet-stream"].includes(upload.type||"application/octet-stream"))return redirectResult(request,"invalid-input");
  const bytes=new Uint8Array(await upload.arrayBuffer()),sha256=createHash("sha256").update(bytes).digest("hex"),client=createServiceSupabaseClient();if(!client)return redirectResult(request,"failed-closed");
  try{
    const duplicate=await client.from("game_packages").select("id",{count:"exact",head:true}).eq("archive_sha256",sha256);if(duplicate.error)return redirectResult(request,"failed-closed");if((duplicate.count??0)>0)return redirectResult(request,"duplicate");
    const inspection=await inspectGameArchive(bytes);
    if(inspection.decision!=="accepted"||!inspection.manifest||!inspection.metadata){
      let objectPath:string|null=null;if(bytes.byteLength<=25*1024*1024){objectPath=`quarantine/games/${randomUUID()}-${normalized}`;const stored=await client.storage.from("game-package-quarantine").upload(objectPath,bytes,{contentType:"application/octet-stream",upsert:false,cacheControl:"private, max-age=0"});if(stored.error)objectPath=null;}
      const evidence=await client.rpc("record_game_package_quarantine",{p_actor_admin_id:access.admin.id,p_normalized_filename:normalized,p_archive_sha256:sha256,p_compressed_size:bytes.byteLength,p_object_path:objectPath,p_findings:inspection.findings});if(evidence.error&&objectPath)await client.storage.from("game-package-quarantine").remove([objectPath]);return redirectResult(request,"quarantined");
    }
    const manifest=inspection.manifest;const lesson=await client.from("content_lessons").select("id,topic_id,title").eq("id",lessonId).neq("publication_state","archived").maybeSingle();if(lesson.error||!lesson.data)return redirectResult(request,"invalid-input");const topic=await client.from("content_topics").select("id,grade_id,title").eq("id",lesson.data.topic_id).neq("publication_state","archived").single();const grade=topic.data?await client.from("content_grades").select("grade_number,title").eq("id",topic.data.grade_id).neq("publication_state","archived").single():null;if(topic.error||!topic.data||!grade||grade.error||!grade.data||grade.data.grade_number!==manifest.grade||topic.data.title!==manifest.topic||lesson.data.title!==manifest.lesson)return redirectResult(request,"taxonomy-mismatch");
    const previous=await client.from("game_packages").select("resource_id,package_version").eq("game_id",manifest.gameId).is("source_package_id",null).order("created_at",{ascending:false}).limit(1).maybeSingle();if(previous.error)return redirectResult(request,"failed-closed");if(previous.data&&compareGamePackageVersions(manifest.version,previous.data.package_version)!==1)return redirectResult(request,"duplicate");
    if(previous.data){const assignment=await client.from("lesson_resource_assignments").select("lesson_id").eq("resource_id",previous.data.resource_id).single();if(assignment.error||assignment.data.lesson_id!==lessonId)return redirectResult(request,"taxonomy-mismatch");}
    const objectPrefix=`games/${manifest.gameId}/${manifest.version}`;const uploadedPaths:string[]=[];const assetEvidence=[] as Array<{path:string;object_path:string;mime_type:string;byte_size:number;sha256:string}>;
    for(const asset of inspection.assets){const objectPath=`${objectPrefix}/${asset.path.toLowerCase()}`;const stored=await client.storage.from("game-packages").upload(objectPath,asset.bytes,{contentType:asset.mimeType,upsert:false,cacheControl:"private, max-age=0"});if(stored.error){await client.storage.from("game-packages").remove(uploadedPaths);return redirectResult(request,"failed-closed");}uploadedPaths.push(objectPath);assetEvidence.push({path:asset.path,object_path:objectPath,mime_type:asset.mimeType,byte_size:asset.bytes.byteLength,sha256:manifest.integrityHashes[asset.path]!});}
    const contentManifest={game_id:manifest.gameId,package_version:manifest.version,package_schema_version:manifest.packageSchemaVersion,minimum_runtime_version:manifest.minimumMathNexaRuntimeVersion};let resourceId:string,resourceVersion:number;
    if(previous.data){const resource=await client.from("content_resources").select("id,current_version_number,lock_version,publication_state").eq("id",previous.data.resource_id).single();if(resource.error||resource.data.publication_state==="archived"){await client.storage.from("game-packages").remove(uploadedPaths);return redirectResult(request,"failed-closed");}const revised=await client.rpc("revise_content_resource",{p_actor_admin_id:access.admin.id,p_resource_id:resource.data.id,p_expected_lock_version:resource.data.lock_version,p_title:manifest.title,p_description:manifest.description,p_thumbnail_path:null,p_tags:["game",manifest.gameId],p_content_manifest:contentManifest});if(revised.error){await client.storage.from("game-packages").remove(uploadedPaths);return redirectResult(request,"failed-closed");}resourceId=resource.data.id;resourceVersion=revised.data;
    }else{const created=await client.rpc("create_content_resource",{p_actor_admin_id:access.admin.id,p_lesson_id:lessonId,p_resource_type:"game",p_slug:manifest.gameId,p_sort_order:sortOrder,p_title:manifest.title,p_description:manifest.description,p_thumbnail_path:null,p_tags:["game",manifest.gameId],p_content_manifest:contentManifest});if(created.error){await client.storage.from("game-packages").remove(uploadedPaths);return redirectResult(request,"failed-closed");}resourceId=created.data;resourceVersion=1;}
    const databaseManifest={package_schema_version:manifest.packageSchemaVersion,game_id:manifest.gameId,version:manifest.version,title:manifest.title,description:manifest.description,grade:manifest.grade,topic:manifest.topic,lesson:manifest.lesson,entry_file:manifest.entryFile,thumbnail:manifest.thumbnail,asset_inventory:manifest.assetInventory,integrity_hashes:manifest.integrityHashes,minimum_mathnexa_runtime_version:manifest.minimumMathNexaRuntimeVersion};
    const registered=await client.rpc("register_game_package",{p_actor_admin_id:access.admin.id,p_resource_id:resourceId,p_resource_version_number:resourceVersion,p_game_id:manifest.gameId,p_package_version:manifest.version,p_package_schema_version:manifest.packageSchemaVersion,p_minimum_runtime_version:manifest.minimumMathNexaRuntimeVersion,p_entry_file:manifest.entryFile,p_thumbnail_file:manifest.thumbnail,p_manifest:databaseManifest,p_metadata:inspection.metadata,p_archive_sha256:sha256,p_compressed_size:bytes.byteLength,p_expanded_size:inspection.expandedSize,p_assets:assetEvidence});if(registered.error){await client.storage.from("game-packages").remove(uploadedPaths);return redirectResult(request,"failed-closed");}
    return redirectResult(request,"saved");
  }catch{return redirectResult(request,"failed-closed")}
}
