import Image from "next/image";
import type{AdminGamePackageSnapshot}from"@/lib/admin/game-package-library";
export function AdminGamePackageLibrary({snapshot,csrfToken,result}:{snapshot:AdminGamePackageSnapshot;csrfToken:string;result?:string}){return <div className="admin-resource-library admin-game-library">
  <header><p className="admin-eyebrow">Grade → Topic → Lesson</p><h1>Game package importer</h1><p>Import owner-created ZIP packages as validated drafts. Package code is never run by the server and previews execute in a restricted iframe.</p></header>
  {result?<div className={`admin-state-banner ${["quarantined","failed-closed","invalid-input","csrf-denied","duplicate"].includes(result)?"admin-state-danger":""}`} role="status"><strong>{result==="saved"?"Package draft imported.":result==="quarantined"?"Unsafe package quarantined.":result==="updated"?"Package state updated.":result==="rolled-back"?"Published package rolled back additively.":result==="archived"?"Package archived.":"The package operation failed closed."}</strong></div>:null}
  {snapshot.state==="unavailable"?<div className="admin-state-banner admin-state-danger" role="alert"><strong>Game packages unavailable.</strong> No write controls are shown.</div>:null}
  {snapshot.state==="ready"&&snapshot.lessons.length===0?<div className="admin-library-empty"><strong>Create the taxonomy first</strong><p>No Grade → Topic → Lesson records exist. No curriculum is inferred from a ZIP.</p></div>:null}
  {snapshot.state==="ready"&&snapshot.lessons.length?<details className="admin-add-resource" open><summary>Add game</summary><form action="/admin/games/upload" method="post" encType="multipart/form-data" className="admin-resource-form">
    <input type="hidden" name="csrfToken" value={csrfToken}/><label><span>Lesson</span><select name="lessonId" required>{snapshot.lessons.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <label><span>Order in lesson</span><input name="sortOrder" type="number" min={1} max={32767} defaultValue={1} required/></label>
    <label className="admin-form-wide"><span>MathNexa ZIP package</span><input name="gamePackage" type="file" accept="application/zip,.zip" required/><small>25 MB compressed, 75 MB expanded, 256 entries maximum. ZIP64, encryption, traversal, bombs, hooks, dynamic code, and external network references are rejected.</small></label>
    <button className="admin-primary-action" type="submit">Upload and validate package</button>
  </form></details>:null}
  {snapshot.state==="ready"?<section aria-labelledby="game-package-list"><div className="admin-section-heading"><div><p className="admin-eyebrow">Immutable versions</p><h2 id="game-package-list">Game packages</h2></div><span>{snapshot.packages.length} versions</span></div>
    {snapshot.packages.length?<div className="admin-library-list">{snapshot.packages.map(item=><article key={item.id}><Image className="admin-package-thumbnail" unoptimized width={240} height={135} src={`/admin/games/${item.id}/thumbnail`} alt={`Thumbnail for ${item.title}`}/><div><p className="admin-eyebrow">{item.hierarchy}</p><h3>{item.title}</h3><p>{item.description}</p></div><dl><div><dt>Package</dt><dd>{item.gameId} v{item.packageVersion}</dd></div><div><dt>Status</dt><dd>{item.state.replaceAll("_"," ")}</dd></div><div><dt>Assets</dt><dd>{item.assetCount}</dd></div></dl>
      <div className="admin-package-actions"><a className="admin-secondary-action" href={`/admin/games/${item.id}/preview`} target="_blank" rel="noreferrer">Preview sandbox</a>
      {item.state==="draft"?<PackageAction action="/admin/games/status" csrfToken={csrfToken} item={item} target="validating" label="Validate package"/>:null}
      {item.state==="validating"?<PackageAction action="/admin/games/status" csrfToken={csrfToken} item={item} target="ready_for_review" label="Mark ready for review"/>:null}
      {item.state==="ready_for_review"?<PackageAction action="/admin/games/status" csrfToken={csrfToken} item={item} target="published" label="Publish game"/>:null}
      {item.state==="published"&&!item.sourcePackageId?<PackageAction action="/admin/games/rollback" csrfToken={csrfToken} item={item} target="rollback" label="Roll back to this version"/>:null}
      {item.state!=="archived"?<PackageAction action="/admin/games/archive" csrfToken={csrfToken} item={item} target="archive" label="Archive game"/>:null}</div></article>)}</div>:<div className="admin-library-empty"><strong>No game packages yet</strong><p>Upload the first Codex-built package; no game content has been fabricated.</p></div>}
  </section>:null}
</div>}
function PackageAction({action,csrfToken,item,target,label}:{action:string;csrfToken:string;item:{id:string;lockVersion:number};target:string;label:string}){return <form action={action} method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="packageId" value={item.id}/><input type="hidden" name="lockVersion" value={item.lockVersion}/><input type="hidden" name="target" value={target}/><button className="admin-secondary-action" type="submit">{label}</button></form>}
