import { readMapPrepDestination } from "@math-vocabulary-hunt/platform-core";

import type { AdminCmsSnapshot } from "@/lib/admin/cms-library";

export function AdminMapPrep({snapshot,csrfToken,result}:Readonly<{snapshot:AdminCmsSnapshot;csrfToken:string;result?:string}>){
  if(snapshot.state==="unavailable")return <div className="admin-state-banner admin-state-danger" role="alert"><strong>MAP Prep configuration unavailable.</strong> Destination controls failed closed.</div>;
  const document=snapshot.documents.find((item)=>item.key==="map-prep");const block=Array.isArray(document?.content.blocks)?document?.content.blocks.find((item)=>item&&typeof item==="object"&&!Array.isArray(item)&&(item as Record<string,unknown>).type==="external-link"):null;const destination=readMapPrepDestination(block);
  return <div className="admin-resource-library admin-map-prep">
    <header className="admin-module-hero"><div><p className="admin-eyebrow">Owner-only external destination</p><h1>MAP Prep destination</h1><p>Configure a reviewed HTTPS destination without embedding or importing external application code. The public link remains unavailable until an enabled configuration is published.</p></div><a className="admin-primary-action" href="#map-prep-editor">{document?"Update destination":"Add destination"}</a></header>
    {result?<div className={`admin-state-banner ${result.includes("failed")||result.includes("invalid")||result.includes("denied")?"admin-state-danger":""}`} role="status"><strong>{result.replaceAll("-"," ")}.</strong> Every accepted update is versioned and audited.</div>:null}
    <section className="admin-destination-status" aria-labelledby="map-prep-status"><div><p className="admin-eyebrow">Public availability</p><h2 id="map-prep-status">{document?.state==="published"&&destination?.enabled?"Available":"Unavailable"}</h2><p>{document?.state==="published"&&destination?.enabled?"The reviewed destination is enabled.":"No enabled published destination is exposed to the public site."}</p></div><dl><div><dt>Publication</dt><dd>{document?.state.replaceAll("_"," ")??"not configured"}</dd></div><div><dt>Validation</dt><dd>{destination?.status??"not verified"}</dd></div><div><dt>Last verified</dt><dd>{destination?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(destination.lastVerifiedAt)):"—"}</dd></div></dl></section>
    <details className="admin-add-resource" id="map-prep-editor" open><summary>{document?"Create a new destination version":"Add MAP Prep destination"}</summary><form action="/admin/map-prep/save" method="post" className="admin-resource-form">
      <input type="hidden" name="csrfToken" value={csrfToken}/>{document?<><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="lockVersion" value={document.lockVersion}/></>:null}
      <label><span>Display label</span><input name="label" defaultValue={destination?.label??"MAP Prep"} maxLength={120} required/></label>
      <label className="admin-form-wide"><span>Destination URL</span><input name="destinationUrl" type="url" inputMode="url" placeholder="https://…" defaultValue={destination?.destinationUrl??""} required/><small>HTTPS only. Local, IP-address, credential-bearing, javascript:, data:, and file: destinations are rejected.</small></label>
      <label className="admin-form-wide"><span>Optional Admin destination URL</span><input name="adminDestinationUrl" type="url" inputMode="url" placeholder="https://…" defaultValue={destination?.adminDestinationUrl??""}/></label>
      <label><span>Open behavior</span><select name="openMode" defaultValue={destination?.openMode??"same_tab"}><option value="same_tab">Same tab</option><option value="new_tab">New tab</option></select></label>
      <label className="admin-checkbox-field"><input name="enabled" type="checkbox" value="true" defaultChecked={destination?.enabled??false}/><span>Enable after publication</span><small>Clearing this keeps the public MAP Prep link unavailable even if the version is published.</small></label>
      <button className="admin-primary-action" type="submit">Validate and save draft</button>
    </form></details>
    {destination?<section className="admin-host-policy" aria-labelledby="map-hosts"><p className="admin-eyebrow">Explicit allowed-host policy</p><h2 id="map-hosts">Approved destination hosts</h2><ul>{destination.allowedHosts.map((host)=><li key={host}><code>{host}</code></li>)}</ul><p>The launch route revalidates the published host against this exact list before redirecting.</p></section>:null}
    {document?<div className="admin-package-actions"><form action="/admin/map-prep/status" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="versionNumber" value={document.version}/><input type="hidden" name="lockVersion" value={document.lockVersion}/>{document.state==="draft"?<button className="admin-secondary-action" name="targetState" value="ready_for_review">Mark ready for review</button>:document.state==="ready_for_review"?<><button className="admin-secondary-action" name="targetState" value="draft">Return to draft</button><button className="admin-primary-action" name="targetState" value="published">Publish destination</button></>:document.state==="published"?<button className="admin-secondary-action" name="targetState" value="archived">Archive destination</button>:null}</form></div>:null}
  </div>;
}
