"use client";

import Image from "next/image";
import { useMemo,useState } from "react";

import type { AdminGameItem,AdminGamePackageSnapshot } from "@/lib/admin/game-package-library";
import { formatAdminDate } from "@/lib/admin/format";

export function AdminGamePackageLibrary({snapshot,csrfToken,result}:Readonly<{snapshot:AdminGamePackageSnapshot;csrfToken:string;result?:string}>){
  const[query,setQuery]=useState("");const[type,setType]=useState("");const[status,setStatus]=useState("");const[launchType,setLaunchType]=useState<"hosted_package"|"external_https">("hosted_package");const[uploading,setUploading]=useState(false);
  const games=useMemo(()=>snapshot.games.filter((item)=>{const text=`${item.title} ${item.description} ${item.stableKey} ${item.skills.join(" ")} ${item.topics.join(" ")}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(!type||item.launchType===type)&&(!status||item.status===status)}),[snapshot.games,query,type,status]);
  return <div className="admin-resource-library admin-game-library">
    <header className="admin-module-hero"><div><p className="admin-eyebrow">Standalone product catalog</p><h1>Games</h1><p>Publish complete MathNexa games without Grade, Topic, or Lesson parents. Canonical, trusted internal, sandboxed package, and approved HTTPS games share one protected catalog.</p></div><a className="admin-primary-action" href="#add-games">Add Game</a></header>
    {result?<GameOutcome value={result}/>:null}
    {snapshot.state==="unavailable"?<div className="admin-state-banner admin-state-danger" role="alert"><strong>Game catalog unavailable.</strong> Authoring controls failed closed.</div>:null}
    {snapshot.state==="ready"?<details className="admin-add-resource" id="add-games" open><summary>Add Game</summary>
      <div className="admin-launch-choice"><label><span>Launch type</span><select value={launchType} onChange={(event)=>setLaunchType(event.target.value as typeof launchType)}><option value="hosted_package">Hosted Package</option><option value="external_https">Approved HTTPS URL</option></select><small>Math Vocabulary Hunt is the protected canonical game and cannot be replaced.</small></label></div>
      {launchType==="hosted_package"?<form action="/admin/games/upload" method="post" encType="multipart/form-data" className="admin-resource-form" onSubmit={()=>setUploading(true)}>
        <input type="hidden" name="csrfToken" value={csrfToken}/><GameMetadataFields/>
        <label className="admin-form-wide"><span>MathNexa ZIP package</span><input name="gamePackage" type="file" accept="application/zip,.zip" required/><small>25 MB compressed, 75 MB expanded, and 256 entries maximum. Traversal, ZIP bombs, hooks, dynamic code, and external network references are quarantined.</small></label>
        <button className="admin-primary-action" type="submit" disabled={uploading}>{uploading?"Validating sandbox package...":"Upload and validate package"}</button><span className="admin-upload-status" aria-live="polite">{uploading?"Upload in progress. Package code will never execute on the server.":""}</span>
      </form>:<form action="/admin/games/external" method="post" className="admin-resource-form"><input type="hidden" name="csrfToken" value={csrfToken}/><GameMetadataFields/>
        <label className="admin-form-wide"><span>HTTPS destination</span><input name="externalUrl" type="url" inputMode="url" placeholder="https://games.example.org/play" required/><small>The server checks DNS, blocks private addresses and redirects, and performs a bounded health request.</small></label>
        <label><span>Allowed host</span><input name="allowedHost" placeholder="games.example.org" pattern="(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}" required/></label>
        <label><span>Thumbnail reference</span><input name="thumbnailReference" defaultValue="builtin:game-card" pattern="(?:builtin|media):[A-Za-z0-9:._-]+" required/></label>
        <button className="admin-primary-action" type="submit">Validate and save draft</button>
      </form>}
    </details>:null}
    {snapshot.state==="ready"?<section aria-labelledby="game-catalog-list"><div className="admin-section-heading"><div><p className="admin-eyebrow">Publishing runway</p><h2 id="game-catalog-list">Game catalog</h2></div><span>{games.length} of {snapshot.games.length}</span></div>
      <div className="admin-library-filters" role="search" aria-label="Search and filter games"><label><span>Search</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search games"/></label><label><span>Launch type</span><select value={type} onChange={(event)=>setType(event.target.value)}><option value="">All launch types</option><option value="canonical">Canonical</option><option value="internal">Internal</option><option value="hosted_package">Hosted package</option><option value="external_https">Approved HTTPS</option></select></label><label><span>Status</span><select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="validating">Validating</option><option value="ready_for_review">Ready for review</option><option value="published">Published</option><option value="maintenance">Maintenance</option><option value="archived">Archived</option></select></label></div>
      {games.length?<div className="admin-library-list">{games.map((game)=><GameCard key={`${game.id}-${game.status}`} game={game} csrfToken={csrfToken}/>)}</div>:<div className="admin-library-empty"><strong>{snapshot.games.length?"No games match these filters":"No games available"}</strong><p>{snapshot.games.length?"Clear or adjust the catalog filters.":"The canonical migration-owned game will be reconciled automatically; retry or contact support if it remains absent."}</p></div>}
    </section>:null}
  </div>;
}

function GameMetadataFields(){return <>
  <label><span>Title</span><input name="title" maxLength={160} required/></label><label><span>Slug</span><input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={96} required/></label>
  <label className="admin-form-wide"><span>Description</span><textarea name="description" rows={4} maxLength={4000} required/></label>
  <label><span>Recommended grade minimum</span><input name="recommendedGradeMin" type="number" min={1} max={12}/></label><label><span>Recommended grade maximum</span><input name="recommendedGradeMax" type="number" min={1} max={12}/></label>
  <label><span>Difficulty</span><select name="difficulty" defaultValue="core"><option value="support">Support</option><option value="core">Core</option><option value="challenge">Challenge</option><option value="adaptive">Adaptive</option><option value="mixed">Mixed</option></select></label><label><span>Display order</span><input name="displayOrder" type="number" min={1} max={32767} defaultValue={2} required/></label>
  <label><span>Skills</span><input name="skills" placeholder="fractions, fluency"/></label><label><span>Topics</span><input name="topics" placeholder="number sense"/></label><label><span>Tags</span><input name="tags" placeholder="whole group, practice"/></label>
</>}

function GameCard({game,csrfToken}:{game:AdminGameItem;csrfToken:string}){
  const preview=game.launchType==="canonical"?"/play":["external_https","internal"].includes(game.launchType)&&game.catalogId?`/admin/games/catalog/${game.catalogId}/preview`:game.packageId?`/admin/games/${game.packageId}/preview`:null;
  const crosscalcV2Preview=game.stableKey==="crosscalc"&&game.catalogId?`/admin/games/catalog/${game.catalogId}/preview?version=0.2.0`:null;
  const crosscalcV2Published=game.stableKey==="crosscalc"&&game.version==="0.2.0";
  return <article className="admin-game-card">
    <div className="admin-game-thumbnail" data-launch={game.launchType}>{game.stableKey==="crosscalc"?<Image unoptimized width={1200} height={675} src="/media/games/crosscalc-v2-rc.webp" alt={`${crosscalcV2Published?"Published":"Release candidate"} CrossCalc V2 number-placement thumbnail`}/>:game.launchType==="hosted_package"&&game.packageId?<Image unoptimized width={240} height={135} src={`/admin/games/${game.packageId}/thumbnail`} alt={`Thumbnail for ${game.title}`}/>:<span aria-hidden="true">{game.launchType==="canonical"?"MVH":game.launchType==="internal"?"NATIVE":"HTTPS"}</span>}</div>
    <div className="admin-game-copy"><p className="admin-eyebrow">{game.launchType.replaceAll("_"," ")}</p><h3>{game.title}</h3><p>{game.description}</p><div className="admin-resource-tags">{[...game.skills,...game.topics,...game.tags].slice(0,6).join(" / ")}</div></div>
    <dl><div><dt>Status</dt><dd><span className="admin-publication-badge" data-state={game.status}>{game.status.replaceAll("_"," ")}</span></dd></div><div><dt>Version</dt><dd>{game.version}</dd></div><div><dt>Order</dt><dd>{game.displayOrder}</dd></div><div><dt>Updated</dt><dd>{formatAdminDate(game.updatedAt)}</dd></div></dl>
    {crosscalcV2Preview&&!crosscalcV2Published?<p className="admin-release-candidate-note"><strong>CrossCalc V2 · Preview Version 0.2.0</strong><span>NOT LIVE · Public subscribers remain on 0.1.0.</span></p>:null}
    {crosscalcV2Published?<p className="admin-release-candidate-note"><strong>CrossCalc V2 · Version 0.2.0</strong><span>LIVE · Published subscriber runtime.</span></p>:null}
    <div className="admin-package-actions">{preview?<a className="admin-secondary-action" href={preview} target="_blank" rel="noreferrer">{crosscalcV2Preview?`Preview live ${crosscalcV2Published?"V2":"V1"}`:"Preview"}</a>:null}{crosscalcV2Preview?<a className="admin-primary-action" href={crosscalcV2Preview} target="_blank" rel="noreferrer">{crosscalcV2Published?"Inspect V2 0.2.0":"Preview V2 0.2.0 · NOT LIVE"}</a>:null}{game.launchType==="hosted_package"&&game.packageId?<HostedActions game={game} csrfToken={csrfToken}/>:game.catalogId?<CatalogActions game={game} csrfToken={csrfToken}/>:null}</div>
    {game.catalogId?<details className="admin-version-history"><summary>Edit and version history</summary><CatalogEdit game={game} csrfToken={csrfToken}/>{game.launchType==="hosted_package"?<ol>{game.packageHistory.map((version)=><li key={version.id}><span>Package {version.version} / {version.status}</span>{version.status==="published"&&version.id!==game.packageId&&game.status!=="archived"?<form action="/admin/games/rollback" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="packageId" value={version.id}/><input type="hidden" name="lockVersion" value={game.packageLockVersion}/><button className="admin-secondary-action">Restore this package</button></form>:null}</li>)}</ol>:<ol>{game.history.map((version)=><li key={version.id}><span>v{version.versionNumber} / {version.status}</span>{version.launchType===game.launchType&&version.versionNumber!==game.history[0]?.versionNumber&&game.status!=="archived"?<form action="/admin/games/catalog/rollback" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="catalogId" value={game.catalogId??""}/><input type="hidden" name="versionId" value={version.id}/><input type="hidden" name="lockVersion" value={game.lockVersion}/><button className="admin-secondary-action">Restore this version</button></form>:null}</li>)}</ol>}</details>:null}
  </article>;
}

function HostedActions({game,csrfToken}:{game:AdminGameItem;csrfToken:string}){const next=game.status==="draft"?["validating","Validate package"]:game.status==="validating"?["ready_for_review","Mark ready for review"]:game.status==="ready_for_review"?["published","Publish game"]:null;return <>{next?<PackageAction action="/admin/games/status" csrfToken={csrfToken} game={game} target={next[0]} label={next[1]} primary={next[0]==="published"}/>:null}{game.status!=="archived"?<PackageAction action="/admin/games/archive" csrfToken={csrfToken} game={game} target="archive" label="Archive game"/>:null}</>}
function PackageAction({action,csrfToken,game,target,label,primary=false}:{action:string;csrfToken:string;game:AdminGameItem;target:string;label:string;primary?:boolean}){return <form action={action} method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="packageId" value={game.packageId??""}/><input type="hidden" name="lockVersion" value={game.packageLockVersion}/><input type="hidden" name="target" value={target}/><button className={primary?"admin-primary-action":"admin-secondary-action"}>{label}</button></form>}
function CatalogActions({game,csrfToken}:{game:AdminGameItem;csrfToken:string}){if(game.launchType==="canonical")return null;return <form action="/admin/games/catalog/status" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="catalogId" value={game.catalogId??""}/><input type="hidden" name="lockVersion" value={game.lockVersion}/>{game.status==="draft"?<button className="admin-primary-action" name="status" value="published">Publish game</button>:game.status==="published"?<><button className="admin-secondary-action" name="status" value="maintenance">Set maintenance</button><button className="admin-secondary-action" name="status" value="archived">Archive game</button></>:game.status==="maintenance"?<><button className="admin-primary-action" name="status" value="published">Resume game</button><button className="admin-secondary-action" name="status" value="archived">Archive game</button></>:null}</form>}
function CatalogEdit({game,csrfToken}:{game:AdminGameItem;csrfToken:string}){return <form action="/admin/games/catalog/update" method="post" className="admin-resource-form admin-catalog-edit"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="catalogId" value={game.catalogId??""}/><input type="hidden" name="launchType" value={game.launchType}/><input type="hidden" name="lockVersion" value={game.lockVersion}/><label><span>Display title</span><input name="title" defaultValue={game.title} maxLength={160} required/></label><label><span>Slug</span><input name="slug" defaultValue={game.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label className="admin-form-wide"><span>Teacher description</span><textarea name="description" defaultValue={game.description} rows={3} required/></label><label><span>Thumbnail reference</span><input name="thumbnailReference" defaultValue={game.thumbnailReference} required/></label><label><span>Grade minimum</span><input name="recommendedGradeMin" type="number" min={1} max={12} defaultValue={game.recommendedGradeMin??""}/></label><label><span>Grade maximum</span><input name="recommendedGradeMax" type="number" min={1} max={12} defaultValue={game.recommendedGradeMax??""}/></label><label><span>Skills</span><input name="skills" defaultValue={game.skills.join(", ")}/></label><label><span>Topics</span><input name="topics" defaultValue={game.topics.join(", ")}/></label><label><span>Tags</span><input name="tags" defaultValue={game.tags.join(", ")}/></label><label><span>Difficulty</span><select name="difficulty" defaultValue={game.difficulty}><option value="support">Support</option><option value="core">Core</option><option value="challenge">Challenge</option><option value="adaptive">Adaptive</option><option value="mixed">Mixed</option></select></label><label><span>Display order</span><input name="displayOrder" type="number" min={1} max={32767} defaultValue={game.displayOrder} required/></label>{game.launchType==="external_https"?<><label className="admin-form-wide"><span>HTTPS destination</span><input name="externalUrl" type="url" defaultValue={game.externalUrl??""} required/></label><label><span>Allowed host</span><input name="allowedHost" defaultValue={game.allowedHost??""} required/></label></>:null}<button className="admin-primary-action">Save new version</button></form>}

function GameOutcome({value}:{value:string}){const danger=["quarantined","failed-closed","invalid-input","csrf-denied","duplicate","unsafe-destination","destination-unreachable","manifest-mismatch"].includes(value);const messages:Record<string,string>={saved:"Package draft imported.",quarantined:"Unsafe package quarantined.",updated:"Package state updated.","rolled-back":"Published version restored.",archived:"Game archived.",published:"Game published.",maintenance:"Game placed in maintenance mode.","external-saved":"Approved HTTPS game saved as a draft.","catalog-updated":"Game metadata saved as a new version.","unsafe-destination":"The external destination was rejected as unsafe.","destination-unreachable":"The external destination did not pass its bounded health check.","manifest-mismatch":"The package game ID must match the entered slug."};return <div className={`admin-state-banner ${danger?"admin-state-danger":""}`} role="status"><strong>{messages[value]??"The game operation failed closed."}</strong></div>}
