"use client";

import Image from "next/image";
import { useMemo, useState } from "react";

import { AdminTaxonomyManager } from "@/components/admin/admin-taxonomy-manager";
import type { AdminGamePackageSnapshot } from "@/lib/admin/game-package-library";
import type { AdminTaxonomySnapshot } from "@/lib/admin/taxonomy";

export function AdminGamePackageLibrary({snapshot,taxonomy,csrfToken,result,taxonomyResult}:Readonly<{snapshot:AdminGamePackageSnapshot;taxonomy:AdminTaxonomySnapshot;csrfToken:string;result?:string;taxonomyResult?:string}>){
  const[query,setQuery]=useState("");const[path,setPath]=useState("");const[uploading,setUploading]=useState(false);
  const packages=useMemo(()=>snapshot.packages.filter((item)=>{const text=`${item.title} ${item.description} ${item.hierarchy} ${item.gameId}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(!path||item.hierarchy.includes(path))}),[snapshot.packages,query,path]);
  return <div className="admin-resource-library admin-game-library">
    <header className="admin-module-hero"><div><p className="admin-eyebrow">Grade → Topic → Lesson</p><h1>Game package importer</h1><p>Import owner-created ZIP packages as validated drafts. Package code is never run by the server and previews execute in a restricted iframe.</p></div><a className="admin-primary-action" href={snapshot.lessons.length?"#add-games":"#games-taxonomy"}>Add Game</a></header>
    {result?<div className={`admin-state-banner ${["quarantined","failed-closed","invalid-input","csrf-denied","duplicate"].includes(result)?"admin-state-danger":""}`} role="status"><strong>{result==="saved"?"Package draft imported.":result==="quarantined"?"Unsafe package quarantined.":result==="updated"?"Package state updated.":result==="rolled-back"?"Published package rolled back additively.":result==="archived"?"Package archived.":"The package operation failed closed."}</strong></div>:null}
    {snapshot.state==="unavailable"?<div className="admin-state-banner admin-state-danger" role="alert"><strong>Game packages unavailable.</strong> No write controls are shown.</div>:null}
    {snapshot.state==="ready"?<AdminTaxonomyManager snapshot={taxonomy} csrfToken={csrfToken} section="games" result={taxonomyResult}/>:null}
    {snapshot.state==="ready"&&snapshot.lessons.length?<details className="admin-add-resource" id="add-games" open><summary>Add Game</summary><form action="/admin/games/upload" method="post" encType="multipart/form-data" className="admin-resource-form" onSubmit={()=>setUploading(true)}>
      <input type="hidden" name="csrfToken" value={csrfToken}/><label><span>Lesson</span><select name="lessonId" required>{snapshot.lessons.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
      <label><span>Order in lesson</span><input name="sortOrder" type="number" min={1} max={32767} defaultValue={1} required/></label>
      <label className="admin-form-wide"><span>MathNexa ZIP package</span><input name="gamePackage" type="file" accept="application/zip,.zip" required/><small>25 MB compressed, 75 MB expanded, 256 entries maximum. ZIP64, encryption, traversal, bombs, hooks, dynamic code, and external network references are rejected.</small></label>
      <button className="admin-primary-action" type="submit" disabled={uploading}>{uploading?"Validating sandbox package…":"Upload and validate package"}</button><span className="admin-upload-status" aria-live="polite">{uploading?"Upload in progress. The package will never execute on the server.":""}</span>
    </form></details>:snapshot.state==="ready"?<div className="admin-library-empty"><strong>Add a curriculum path first</strong><p>The Add Game action is ready. Create a Grade, Topic, and Lesson above before assigning a ZIP manifest.</p></div>:null}
    {snapshot.state==="ready"?<section aria-labelledby="game-package-list"><div className="admin-section-heading"><div><p className="admin-eyebrow">Immutable versions</p><h2 id="game-package-list">Game packages</h2></div><span>{packages.length} of {snapshot.packages.length}</span></div>
      <div className="admin-library-filters" role="search" aria-label="Search and filter games"><label><span>Search</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search games"/></label><label><span>Curriculum path</span><select value={path} onChange={(event)=>setPath(event.target.value)}><option value="">All paths</option>{taxonomy.lessons.map((lesson)=><option key={lesson.id} value={`${lesson.gradeTitle} / ${lesson.topicTitle} / ${lesson.title}`}>{lesson.gradeTitle} / {lesson.topicTitle} / {lesson.title}</option>)}</select></label></div>
      {packages.length?<div className="admin-library-list">{packages.map(item=><article key={item.id}><Image className="admin-package-thumbnail" unoptimized width={240} height={135} src={`/admin/games/${item.id}/thumbnail`} alt={`Thumbnail for ${item.title}`}/><div><p className="admin-eyebrow">{item.hierarchy}</p><h3>{item.title}</h3><p>{item.description}</p></div><dl><div><dt>Package</dt><dd>{item.gameId} v{item.packageVersion}</dd></div><div><dt>Status</dt><dd><span className="admin-publication-badge" data-state={item.state}>{item.state.replaceAll("_"," ")}</span></dd></div><div><dt>Assets</dt><dd>{item.assetCount}</dd></div><div><dt>Checksum</dt><dd>Verified at import</dd></div></dl>
        <div className="admin-package-actions"><a className="admin-secondary-action" href={`/admin/games/${item.id}/preview`} target="_blank" rel="noreferrer">Preview sandbox</a>
        {item.state==="draft"?<PackageAction action="/admin/games/status" csrfToken={csrfToken} item={item} target="validating" label="Validate package"/>:null}
        {item.state==="validating"?<PackageAction action="/admin/games/status" csrfToken={csrfToken} item={item} target="ready_for_review" label="Mark ready for review"/>:null}
        {item.state==="ready_for_review"?<PackageAction action="/admin/games/status" csrfToken={csrfToken} item={item} target="published" label="Publish game" primary/>:null}
        {item.state==="published"&&!item.sourcePackageId?<PackageAction action="/admin/games/rollback" csrfToken={csrfToken} item={item} target="rollback" label="Restore this published version"/>:null}
        {item.state!=="archived"?<PackageAction action="/admin/games/archive" csrfToken={csrfToken} item={item} target="archive" label="Archive game"/>:null}</div></article>)}</div>:<div className="admin-library-empty"><strong>{snapshot.packages.length?"No games match these filters":"No game packages yet"}</strong><p>{snapshot.packages.length?"Clear or adjust the search filters.":"Use Add Game after creating a reviewed curriculum path."}</p></div>}
    </section>:null}
  </div>;
}
function PackageAction({action,csrfToken,item,target,label,primary=false}:{action:string;csrfToken:string;item:{id:string;lockVersion:number};target:string;label:string;primary?:boolean}){return <form action={action} method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="packageId" value={item.id}/><input type="hidden" name="lockVersion" value={item.lockVersion}/><input type="hidden" name="target" value={target}/><button className={primary?"admin-primary-action":"admin-secondary-action"} type="submit">{label}</button></form>}
