import { randomUUID } from "node:crypto";

import type { AdminAccountView, AdminAccountsSnapshot } from "@/lib/admin/account-operations";
import { AdminOperationDialog } from "./admin-operation-dialog";

const date = (value:string|null) => value ? new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "not available";
const key=(account:AdminAccountView,operation:string)=>`phase8g:${account.id}:${operation}:${randomUUID()}`;
const dialog=(account:AdminAccountView,csrfToken:string,operation:string,label:string,description:string,reasonRequired=false,danger=false,extra:Readonly<{durationDays?:boolean;refundRequestId?:string}>={})=><AdminOperationDialog key={`${operation}-${extra.refundRequestId??""}`} csrfToken={csrfToken} targetUserId={account.id} operation={operation} idempotencyKey={key(account,operation)} label={label} description={description} reasonRequired={reasonRequired} danger={danger} {...extra}/>;

export function AdminAccountsLibrary({snapshot,csrfToken,result,mode}:Readonly<{snapshot:AdminAccountsSnapshot;csrfToken:string;result?:string;mode:"users"|"subscriptions"}>){return <div className="admin-resource-library admin-accounts-library">
  <header><p className="admin-eyebrow">Owner-only · minimized identity view</p><h1>{mode==="users"?"Accounts and access":"Subscriptions and refund reviews"}</h1><p>Safe operational summaries exclude passwords, hashes, MFA data, session tokens, full IP histories, card data, and provider secrets. Every mutation is bounded, idempotent, session-bound, and audited.</p></header>
  {result?<div className={`admin-state-banner ${result.includes("failed")||result.includes("denied")||result.includes("invalid")||result.includes("required")||result.includes("unavailable")?"admin-state-danger":""}`} role="status"><strong>{result.replaceAll("-"," ")}.</strong> Server-owned account and provider state remains authoritative.</div>:null}
  {snapshot.state==="unavailable"?<div className="admin-state-banner admin-state-danger" role="alert"><strong>Account operations unavailable.</strong> No customer data or mutation controls are displayed.</div>:null}
  {snapshot.state==="ready"?<><div className="admin-state-banner"><strong>{snapshot.accounts.length} consumer accounts loaded.</strong>{snapshot.truncated?" The view is bounded to the first 100 Auth identities; use an exact account ID in a future approved search workflow.":" No fabricated account records are shown."}</div>
  {snapshot.accounts.length?<div className="admin-account-list">{snapshot.accounts.map(account=><article className="admin-account-card" key={account.id}>
    <header><div><p className="admin-eyebrow">{account.status.replaceAll("_"," ")}</p><h2>{account.email}</h2><code>{account.id}</code></div><span data-tone={account.status==="active"?"good":"warning"}>{account.confirmed?"confirmed":"unconfirmed"}</span></header>
    <dl className="admin-account-facts"><div><dt>Created</dt><dd>{date(account.createdAt)}</dd></div><div><dt>Last authenticated</dt><dd>{date(account.lastAuthenticatedAt)}</dd></div><div><dt>Trial</dt><dd>{account.trial}</dd></div><div><dt>Subscription</dt><dd>{account.subscription}</dd></div><div><dt>Current entitlement</dt><dd>{account.entitlement}{account.complimentaryExpiresAt?` through ${date(account.complimentaryExpiresAt)}`:""}</dd></div><div><dt>Deletion</dt><dd>{account.deletion}</dd></div><div className="admin-account-wide"><dt>Consent versions</dt><dd>{account.consentVersions}</dd></div></dl>
    <section aria-label={`Safe operations for ${account.email}`}><h3>Safe operations</h3><div className="admin-operation-grid">
      {!account.confirmed?dialog(account,csrfToken,"resend-confirmation","Resend confirmation","Send a new confirmation message through the configured Auth email provider."):null}
      {dialog(account,csrfToken,"revoke-sessions","Revoke active sessions","Invalidate this account's active Auth sessions. A fresh owner session and reason are required.",true,true)}
      {account.status==="active"?dialog(account,csrfToken,"suspend","Suspend account","Deny protected account and game access and revoke active Auth sessions without changing billing authority.",true,true):account.status==="suspended"?dialog(account,csrfToken,"restore","Restore account","Restore application access only. Deletion-pending accounts cannot be restored here.",true):null}
      {account.complimentaryExpiresAt?dialog(account,csrfToken,"remove-complimentary","Remove complimentary access","End the active owner grant without changing Stripe subscription records.",true,true):dialog(account,csrfToken,"grant-complimentary","Grant complimentary access","Create one time-limited access grant, independently of authoritative billing.",true,false,{durationDays:true})}
      {dialog(account,csrfToken,"open-portal","Open Customer Portal","Open a short-lived, provider-validated Stripe Customer Portal session. The URL is never stored.")}
      {dialog(account,csrfToken,"cancel-at-period-end","Open cancellation portal","Open the validated portal where cancellation is constrained to the end of the paid period.")}
      {dialog(account,csrfToken,"submit-refund-review","Submit refund review","Create or reuse a review request only when a verified first charge is inside the configured review window.")}
      {account.refunds.filter(refund=>["requested","reviewing"].includes(refund.status)).map(refund=>dialog(account,csrfToken,"deny-refund-review","Deny refund review",`Record a reviewed denial for request ${refund.id}. No Stripe amount is changed.`,true,true,{refundRequestId:refund.id}))}
      {dialog(account,csrfToken,"emergency-revoke","Emergency revoke access","Immediately suspend application access, revoke Auth sessions, end complimentary access, and deny the derived game entitlement. Billing evidence remains intact.",true,true)}
    </div></section>
    <section className="admin-readonly-workflows" aria-labelledby={`readonly-${account.id}`}><h3 id={`readonly-${account.id}`}>Read-only safeguards</h3><p><strong>Refund approval:</strong> unavailable until an exact eligible Stripe payment can be provider-verified and refunded idempotently. <strong>Permanent deletion:</strong> unavailable until cancellation, retention, legal hold, and identity deletion checkpoints are satisfied.</p></section>
    <details><summary>Support notes and audit history</summary><form action="/admin/users/note" method="post" className="admin-support-note-form"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="targetUserId" value={account.id}/><label><span>Add immutable support note</span><textarea name="note" minLength={3} maxLength={1000} required/><small>Never include secrets, payment data, or student information.</small></label><button className="admin-secondary-action">Add audited note</button></form>
      <div className="admin-account-evidence"><div><h4>Support notes</h4>{account.notes.length?<ol>{account.notes.map(note=><li key={note.id}><span>{date(note.createdAt)}</span><p>{note.note}</p></li>)}</ol>:<p>None recorded.</p>}</div><div><h4>Relevant audit</h4>{account.audit.length?<ol>{account.audit.map((event,index)=><li key={`${event.createdAt}-${index}`}><span>{date(event.createdAt)}</span><p>{event.action.replaceAll("."," ")}</p></li>)}</ol>:<p>None recorded.</p>}</div></div>
    </details>
  </article>)}</div>:<div className="admin-library-empty"><strong>No consumer accounts</strong><p>Auth-only admin identities are intentionally excluded from the consumer operations view.</p></div>}</>:null}
</div>}
