import { CMS_DOCUMENT_KEYS,MEDIA_KINDS } from "@math-vocabulary-hunt/platform-core";
import type { AdminCmsSnapshot } from "@/lib/admin/cms-library";

const legal=new Set(["terms","privacy","cancellation","refunds"]);
function field(source:Record<string,unknown>,key:string){return typeof source[key]==="string"?source[key] as string:""}
export function AdminCmsLibrary({snapshot,csrfToken,result}:Readonly<{snapshot:AdminCmsSnapshot;csrfToken:string;result?:string}>){return <div className="admin-resource-library">
  <header><p className="admin-eyebrow">Allowlisted structured content</p><h1>CMS and legal content</h1><p>Draft, review, publish, and roll back structured blocks. Raw HTML and JavaScript are rejected. Legal publication is immutable and versioned.</p></header>
  {result?<div className={`admin-state-banner ${result.includes("failed")||result.includes("invalid")||result.includes("denied")?"admin-state-danger":""}`} role="status"><strong>{result.replaceAll("-"," ")}.</strong> Server-owned state remains authoritative.</div>:null}
  {snapshot.state==="unavailable"?<div className="admin-state-banner admin-state-danger" role="alert"><strong>CMS unavailable.</strong> No mutation controls are shown.</div>:null}
  {snapshot.state==="ready"?<><details open className="admin-add-resource"><summary>Create structured draft</summary><form action="/admin/cms/save" method="post" className="admin-resource-form">
    <input type="hidden" name="csrfToken" value={csrfToken}/><label><span>Content key</span><select name="key">{CMS_DOCUMENT_KEYS.filter(key=>key!=="map-prep").map(key=><option key={key} value={key}>{key.replaceAll("-"," ")}</option>)}</select><small>MAP Prep is managed in its dedicated destination module.</small></label>
    <label><span>Title</span><input name="title" maxLength={160} required/></label><label className="admin-form-wide"><span>Description</span><textarea name="description" maxLength={5000}/></label>
    <label><span>SEO title</span><input name="seoTitle" maxLength={70}/></label><label><span>SEO description</span><input name="seoDescription" maxLength={180}/></label>
    <label><span>Social title</span><input name="socialTitle" maxLength={100}/></label><label><span>Social description</span><input name="socialDescription" maxLength={240}/></label>
    <label className="admin-form-wide"><span>Structured blocks (JSON array)</span><textarea name="blocks" rows={10} defaultValue={'[{"type":"section","heading":"Section heading","body":"Reviewed plain text."}]'} required/><small>Allowed: hero, section, feature-list, announcement, faq-list, link-list, external-link, legal-section. No raw HTML.</small></label>
    <button className="admin-primary-action" type="submit">Validate and save draft</button></form></details>
    <section aria-labelledby="cms-documents"><div className="admin-section-heading"><div><p className="admin-eyebrow">Version ledger</p><h2 id="cms-documents">CMS documents</h2></div><span>{snapshot.documents.length} records</span></div>
    {snapshot.documents.length?<div className="admin-library-list">{snapshot.documents.map(document=><article key={document.id}><div><p className="admin-eyebrow">{legal.has(document.key)?"Legal policy":"Structured content"}</p><h3>{document.key.replaceAll("-"," ")}</h3><p>Version {document.version} · {document.state.replaceAll("_"," ")}{document.publishedVersion?` · published v${document.publishedVersion}`:""}</p></div>
      {document.state!=="archived"?<details><summary>Create a new draft version</summary><form action="/admin/cms/save" method="post" className="admin-resource-form"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="lockVersion" value={document.lockVersion}/><input type="hidden" name="key" value={document.key}/>
        <label><span>Title</span><input name="title" defaultValue={field(document.content,"title")} required/></label><label><span>Description</span><textarea name="description" defaultValue={field(document.content,"description")}/></label><label><span>SEO title</span><input name="seoTitle" defaultValue={field(document.content,"seoTitle")}/></label><label><span>SEO description</span><input name="seoDescription" defaultValue={field(document.content,"seoDescription")}/></label><label><span>Social title</span><input name="socialTitle" defaultValue={field(document.content,"socialTitle")}/></label><label><span>Social description</span><input name="socialDescription" defaultValue={field(document.content,"socialDescription")}/></label><label className="admin-form-wide"><span>Structured blocks</span><textarea name="blocks" rows={8} defaultValue={JSON.stringify(document.content.blocks??[],null,2)} required/></label><button className="admin-secondary-action">Validate new draft</button></form></details>:null}
      <form action="/admin/cms/status" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="versionNumber" value={document.version}/><input type="hidden" name="lockVersion" value={document.lockVersion}/>
        {document.state==="draft"?<button name="targetState" value="ready_for_review" className="admin-secondary-action">Submit for review</button>:document.state==="ready_for_review"?<><button name="targetState" value="draft" className="admin-secondary-action">Return to draft</button><button name="targetState" value="published" className="admin-primary-action">Publish reviewed version</button></>:document.state==="published"?<button name="targetState" value="archived" className="admin-secondary-action">Archive current page</button>:null}
      </form></article>)}</div>:<div className="admin-library-empty"><strong>No CMS documents yet</strong><p>No public copy has been fabricated.</p></div>}</section></>:null}
</div>}

export function AdminMediaLibrary({snapshot,csrfToken,result}:Readonly<{snapshot:AdminCmsSnapshot;csrfToken:string;result?:string}>){return <div className="admin-resource-library"><header><p className="admin-eyebrow">Private originals · controlled derivatives</p><h1>Media library</h1><p>Upload images, audio, and PDFs. Image dimensions are decoded and optimized WebP derivatives are generated before review.</p></header>
  {result?<div className={`admin-state-banner ${result.includes("failed")||result.includes("invalid")||result==="quarantined"?"admin-state-danger":""}`} role="status"><strong>{result.replaceAll("-"," ")}.</strong></div>:null}
  {snapshot.state==="ready"?<><details open className="admin-add-resource"><summary>Add media</summary><form action="/admin/media/upload" method="post" encType="multipart/form-data" className="admin-resource-form"><input type="hidden" name="csrfToken" value={csrfToken}/>
    <label><span>Version target</span><select name="replace"><option value="">New media identity</option>{snapshot.media.map(media=><option key={media.id} value={`${media.id}|${media.lockVersion}|${media.version}`}>New version of {media.key}</option>)}</select></label>
    <label><span>Stable key</span><input name="key" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label><span>Kind</span><select name="kind">{MEDIA_KINDS.map(kind=><option key={kind}>{kind}</option>)}</select><small>For a replacement, select the same kind as the existing asset.</small></label>
    <label className="admin-form-wide"><span>File</span><input name="media" type="file" accept="image/png,image/jpeg,image/webp,audio/mpeg,audio/ogg,audio/wav,application/pdf" required/></label>
    <label><span>Alt text</span><input name="altText" maxLength={500}/><small>Required for visual media.</small></label><label><span>Caption</span><input name="caption" maxLength={1000}/></label><label><span>Attribution</span><input name="attribution" maxLength={1000}/></label><label><span>License</span><input name="license" maxLength={200} required/></label>
    <button className="admin-primary-action">Validate and save private media</button></form></details>
    <div className="admin-library-list">{snapshot.media.map(media=><article key={media.id}><div><p className="admin-eyebrow">{media.kind}</p><h3>{media.key}</h3><p>{media.filename} · {media.mimeType}{media.width?` · ${media.width}×${media.height}`:""}</p></div><dl><div><dt>Status</dt><dd>{media.state.replaceAll("_"," ")}</dd></div><div><dt>Usage</dt><dd>{media.inUse?"in use":"unused"}</dd></div></dl>
      <form action="/admin/media/status" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="mediaId" value={media.id}/><input type="hidden" name="lockVersion" value={media.lockVersion}/>{media.state==="draft"?<button name="targetState" value="ready_for_review">Submit for review</button>:media.state==="ready_for_review"?<button name="targetState" value="published">Publish derivative</button>:null}</form>
      {!media.inUse?<form action="/admin/media/archive" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="mediaId" value={media.id}/><input type="hidden" name="lockVersion" value={media.lockVersion}/><button className="admin-secondary-action">Archive</button></form>:null}
    </article>)}</div></>:<div className="admin-state-banner admin-state-danger" role="alert"><strong>Media library unavailable.</strong></div>}</div>}
