import { readMapPrepDestination } from "@math-vocabulary-hunt/platform-core";
import Link from "next/link";

import type { AdminCmsSnapshot } from "@/lib/admin/cms-library";

export function AdminMapPrep({snapshot,csrfToken,result}:Readonly<{snapshot:AdminCmsSnapshot;csrfToken:string;result?:string}>){
  if(snapshot.state==="unavailable")return <div className="admin-state-banner admin-state-danger" role="alert"><strong>MAP Prep configuration unavailable.</strong> Destination controls failed closed.</div>;
  const document=snapshot.documents.find((item)=>item.key==="map-prep");const block=Array.isArray(document?.content.blocks)?document?.content.blocks.find((item)=>item&&typeof item==="object"&&!Array.isArray(item)&&(item as Record<string,unknown>).type==="external-link"):null;const destination=readMapPrepDestination(block);const raw=block&&typeof block==="object"&&!Array.isArray(block)?block as Record<string,unknown>:{};const available=document?.state==="published"&&destination?.enabled;
  return <div className="admin-resource-library admin-map-prep">
    <header className="admin-module-hero"><div><p className="admin-eyebrow">Owner-only external destination</p><h1>MAP Prep destination</h1><p>Validate one explicit HTTPS host, preview its customer state, and publish without embedding or importing external application code.</p></div><a className="admin-primary-action" href="#map-prep-editor">Edit Destination</a></header>
    {result?<div className={`admin-state-banner ${result.includes("failed")||result.includes("invalid")||result.includes("denied")?"admin-state-danger":""}`} role="status"><strong>{result.replaceAll("-"," ")}.</strong> Every accepted update is versioned and audited.</div>:null}
    <section className="admin-destination-status" aria-labelledby="map-prep-status"><div><p className="admin-eyebrow">Public-preview state</p><h2 id="map-prep-status">{available?"Enabled":"Unavailable"}</h2><p>{available?destination.publicDescription||"The reviewed MAP Prep destination is enabled.":"No enabled, published, server-verified destination is exposed to customers."}</p><Link className="admin-secondary-action" href="/map-prep" target="_blank">Open public preview</Link></div><dl><div><dt>Publication</dt><dd>{document?.state.replaceAll("_"," ")??"not configured"}</dd></div><div><dt>Health</dt><dd>{String(raw.healthStatus??destination?.status??"not verified")}</dd></div><div><dt>Last health check</dt><dd>{typeof raw.lastHealthCheck==="string"?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(raw.lastHealthCheck)):"Not run"}</dd></div><div><dt>Last verified</dt><dd>{destination?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(destination.lastVerifiedAt)):"Not verified"}</dd></div></dl></section>
    <details className="admin-add-resource" id="map-prep-editor" open><summary>{document?"Create a new destination version":"Add MAP Prep destination"}</summary><form action="/admin/map-prep/save" method="post" className="admin-resource-form">
      <input type="hidden" name="csrfToken" value={csrfToken}/>{document?<><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="lockVersion" value={document.lockVersion}/></>:null}
      <label><span>Display label</span><input name="label" defaultValue={destination?.label??"MAP Prep"} maxLength={120} required/></label>
      <label className="admin-form-wide"><span>Public description</span><textarea name="publicDescription" defaultValue={destination?.publicDescription??""} maxLength={500} rows={3} required/><small>Shown only after an enabled version is published.</small></label>
      <label className="admin-form-wide"><span>Destination URL</span><input name="destinationUrl" type="url" inputMode="url" placeholder="https://example.org/path" defaultValue={destination?.destinationUrl??""} required/><small>HTTPS only. Local, IP-address, credential-bearing, unsafe-protocol, and redirecting destinations are rejected.</small></label>
      <label className="admin-form-wide"><span>Optional Admin destination URL</span><input name="adminDestinationUrl" type="url" inputMode="url" placeholder="https://example.org/admin" defaultValue={destination?.adminDestinationUrl??""}/><small>When provided, it must use the same explicitly approved host.</small></label>
      <label><span>Allowed host</span><input name="allowedHost" inputMode="url" placeholder="example.org" defaultValue={destination?.allowedHosts[0]??""} pattern="[A-Za-z0-9.-]+" required/><small>The server resolves this host and performs a bounded no-redirect health check before saving.</small></label>
      <label><span>Open behavior</span><input value="Same tab" readOnly aria-describedby="map-prep-open-mode-help"/><input name="openMode" type="hidden" value="same_tab"/><small id="map-prep-open-mode-help">MAP Prep V1 uses the protected same-tab launch route.</small></label>
      <label className="admin-checkbox-field"><input name="enabled" type="checkbox" value="true" defaultChecked={destination?.enabled??false}/><span>Enable after publication</span><small>Clearing this keeps the public MAP Prep link unavailable even if the version is published.</small></label>
      <div className="admin-sticky-actions admin-form-wide"><button className="admin-primary-action" type="submit">Test destination and save draft</button><span>Server health verification is required; no browser value can authorize publication.</span></div>
    </form></details>
    {destination?<section className="admin-host-policy" aria-labelledby="map-hosts"><p className="admin-eyebrow">Explicit allowed-host policy</p><h2 id="map-hosts">Approved destination host</h2><ul>{destination.allowedHosts.map((host)=><li key={host}><code>{host}</code></li>)}</ul><p>The launch route revalidates the published host against this exact list before redirecting.</p></section>:null}
    {document?<div className="admin-package-actions"><form action="/admin/map-prep/status" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="versionNumber" value={document.version}/><input type="hidden" name="lockVersion" value={document.lockVersion}/>{document.state==="draft"?<button className="admin-secondary-action" name="targetState" value="ready_for_review">Mark ready for review</button>:document.state==="ready_for_review"?<><button className="admin-secondary-action" name="targetState" value="draft">Return to draft</button><button className="admin-primary-action" name="targetState" value="published">Publish verified destination</button></>:document.state==="published"?<button className="admin-secondary-action" name="targetState" value="archived">Archive destination</button>:null}</form></div>:null}
  </div>;
}
